---
title: "discussion"
author: "Keana Richards"
date: "17/3/2022"
output: word_document
---
#### Summary of main experimental results

There is no evidence that the limited opportunity to prepare affected participants' choice to compete, nor did we find evidence of the anticipated interaction effect between gender and condition. Thus, it appears that gender differences in competitiveness are unaffected by having had the opportunity to prepare for a limited, pre-specified amount of time.   

In fact, the gender difference in competitiveness itself, like in Study 1, does not hold when risk attitudes, confidence, and task scores are included in the model, suggesting the difference was explained by those variables. In this way, our study deviates from previous research suggesting that competitiveness is a stand-alone trait [@Niederle2007], and is more in line with recent evidence that competitiveness is explained by other factors (e.g., confidence or risk attitudes) [@Gillen2019; @Veldhuizen2017]. In line with this argument, we replicate the finding both within the broader literature and in the previous study that women are more risk averse and less confident than men. We discuss these findings across the studies of Chapter 1 in light of broader literature on whether competitiveness is a stand-alone trait further in the overall discussion section.    

Contrary to Study 1, the gender differences in task scores observed when gender is included as the only predictor appear to be explained by differences in risk attitudes and confidence, since the effect of gender on task score is no longer significant when those predictors are included in the model. Thus, based on these first two sets of results, it is not entirely clear yet if there are gender differences in performance on the multiplication task used in the study. 

#### Gender differences in preparation and gender stereotypes 

Even though we do not have evidence within the context of this study that there is a gender difference in competitiveness or performance on the multiplication task when controlling for other variables, women still chose to prepare more than men - regardless of which payment scheme they ultimately selected, their risk attitudes, confidence, or task scores. At the same time, we have evidence that the choice to compete in general is related to a participants' choice to prepare, such that individuals who chose the competitive payment scheme chose to prepare at higher rates than those who chose the non-competitive payment scheme. We replicate the effects found in Study 1 when asking participants about their perceptions of these gender differences in performance, competitiveness, and preparation, such that participants were 1) significantly more likely to say that women prepare more than men both in general and on the multiplication task, despite 2) competing less and 3) performing just as well as men. Thus, we have further evidence based on participants' responses to the incentivized questions about their beliefs that there are gender stereotypes about preparation, which may in turn affect gender differences in the choice to prepare (see Section \@ref(gender-stereotypes-and-practicing) for a review of the literature showing how gender stereotypes affect subsequent behavior).

On top of the gender differences in practicing and perceptions of said gender differences, we again explored whether these perceptions aligned with individuals' practicing behaviors. We find evidence that women were especially likely to prepare for the task if they believed that women prepare more than men, both in general on most tasks and specifically within the context of the multiplication task. Again, we highlight the importance of future research in testing the direction of these effects, since we cannot attest to whether perceptions lead to behavior or whether behavior leads to perceptions directly using this dataset. 

#### Post-manipulation measures 


Finally, we explore the new post-manipulation measures that are specific to this study. First, we find that feelings of preparedness are related to the choice to prepare. In light of the other findings, this result implies that feelings of preparedness do not derive from the required amount of preparation that one completes (that is, random assignment to condition within the context of this study), but instead, the choice to spend extra time preparing over and above what is required^[Though it is worth noting that the effect of the choice to prepare may reflect the effects of variables that we are not measuring, while the random assignment to condition is estimating the causal effect of preparation on feelings of preparedness. It would be important to consider possible confounds for the effect of the choice to prepare and try to adequately capture those in future research]. Additionally, the fact that gender does not predict feelings of preparedness, despite women choosing to prepare more, has potentially important implications if replicated. That is, women may prepare more than men, yet still feel as though they are less prepared relative to others. We explore this possibility in the study of Chapter 2. These results would suggest that women's greater decisions to prepare may only contribute to feelings of preparedness that are not significantly different than men's, if they contribute at all. However, it is unclear whether the choice to prepare may be related to other variables not captured in this study that predict feelings of preparedness. Thus, future studies should explore women's and men's feelings of preparedness both before and after the choice to prepare as a way to try to address the question of what is driving the effect. 

On top of the question about feelings of preparedness after completing the practice and task itself, we also asked participants to indicate their feelings about the multiplication task itself, and more specifically, how fatigued they felt after completing the task and how interested they were in the task. With regards to the question about fatigue, both participants in the limited preparation condition and participants who chose to prepare reported significantly higher levels of fatigue than participants who did not choose to prepare and were not required to. Yet, women did not report feeling significantly more fatigued than men, despite, again, choosing to prepare at significantly higher rates. Thus, women's higher rates of preparation did not seem to have negative effects on this measure attempting to capture potential negative effects of preparing. When testing effects of gender, condition, and practice choice on interest, we find that women were significantly less interested in the task, while participants who chose to prepare tended to be more interested in the task. Finally, we show that gender does not predict field-specific ability beliefs - in other words, men and women's emphasis on the importance of hard work for success (at least within the domain of math), do not appear to be significantly different in this study. This is the only study in the dissertation that includes the measures of feelings of preparedness, fatigue, and interest, and as such, replication of these results would be important to confirm they are not false positives [@Coffman2015]. 

#### Summary 

Overall, we find from Study 2 of Chapter 1 that our manipulation of the limited opportunity to prepare did not reduce the gender difference in competitiveness. We show that the gender difference in competitiveness itself is explained by gender differences in risk attitudes, task scores, and confidence. Although the manipulation did not have the anticipated effects on gender differences in competitiveness, we replicate the effect that women chose to prepare more than men, which aligned with beliefs about gender differences in preparation. We also replicate the interaction effect between gender and beliefs about gender differences in preparation on the choice to prepare, again suggesting that women's preparation behaviors may have been influenced by beliefs about gender differences in preparation.

Finally, we explored participants' experiences while completing the multiplication task through questions about their feelings of preparedness, fatigue, and interest. We find that the limited preparation condition did not predict feelings of preparedness, but instead participants who chose to prepare were significantly more likely to report feeling more prepared for the multiplication task. For the measure of fatigue, participants who chose to prepare were significantly more likely to report feeling fatigued after completing the task. Finally, women were significantly less interested in the task, while participants who chose to prepare tended to be more interested in the task. Since this is the only study across all studies within this dissertation that employs these measures, and thus, we have not been able to replicate these effects, we encourage future research to ensure these effects are indeed replicable.  

Since we did not find evidence that the limited opportunity to prepare affected gender differences in competitiveness, the last study in Chapter 1 tests experimentally whether having the unlimited opportunity to prepare would affect the gender gap in competitiveness. It is possible that participants in the limited preparation condition may have felt like they were not getting any additional preparation above and beyond what other participants were receiving because they could not choose how much they prepared, and thus, they did not feel like the preparation would have helped their performance substantially more than it would have helped other participants. If this possible explanation for the null effect in Study 2 is correct, we should expect to see an effect of unlimited preparation on reducing the gender difference in competitiveness. 

