---
title: "cut"
author: "Keana Richards"
date: "8/3/2022"
output: html_document
---

pulled from after cite in intro: "For instance, in a study examining school-aged children’s approach to learning math, researchers found that girls, compared to boys, reported being more motivated to “master” their schoolwork and engage in more effortful learning strategies [@Kenney-Benson2006]."

Additionally, as shown in Chapter 2, I discovered a sizable gender difference in effort, where women were more likely than men to choose to prepare before completing a multiplication task (Richards et al., in prep). The goal of this work was to explore how preparation might influence women’s willingness to compete. The first preliminary study in this line of work manipulated participants’ (_N_ = `r nrow(clean)`) knowledge of whether they would have unlimited time to prepare before they made their decision to compete. We expected that participants who knew they had time to prepare would be more inclined to compete compared to participants who were not aware of the opportunity to prepare. While we did not find that knowledge of preparation affected participants’ decision to compete, there was a sizable gender difference in the choice to prepare. Controlling for the decision to compete, women were `r round((exp(coef(primary_hyp2))[2] - 1)*100, digits = 0)`% more likely to choose to prepare compared to men when offered the opportunity, `r apa_print(primary_hyp2)$full_result$genderWoman` (see Figure 1). Additionally, at the end of the experiment, participants were incentivized to correctly predict which gender they believed would be more likely to prepare in the study. Both men (`r round(ctable(clean$gender, clean$perc_task_gender_pract)$proportions[4]*100, digits = 0)`%) and women (`r round(ctable(clean$gender, clean$perc_task_gender_pract)$proportions[5]*100, digits = 0)`%) correctly believed that women would spend more time preparing for the task, `r apa_print(exploratory7c, n= nrow(clean))$statistic`. We found similar results when asking participants which gender prepares more in general - `r round(ctable(clean$gender, clean$perc_gen_gender_pract)$proportions[4]*100, digits = 0)`% of men and `r round(ctable(clean$gender, clean$perc_gen_gender_pract)$proportions[5]*100, digits= 0)`% of women believed that women prepare more in general, `r apa_print(exploratory7c, n= nrow(clean))$statistic`. 


In a follow-up study designed to examine the role of forced preparation on the decision to compete, we recruited `r nrow(clean)` participants from Amazon Mechanical Turk (MTurk), who were assigned to either a condition where they were required to complete several rounds of practice for the upcoming paid multiplication task or several rounds of a filler task before choosing their payment scheme. Again, our manipulation had no effect on the choice to compete in men or women. However, after completing their respective rounds of practice and choosing their payment scheme, participants in both conditions had the option to spend (extra) time preparing for the multiplication task. Here, we replicated the effect of gender on preparation, where `r round(ctable(clean$gender, clean$pract_choice)$proportions[5]*100, digits =0)`% of women and `r round(ctable(clean$gender, clean$pract_choice)$proportions[4]*100, digits = 0)`% of men chose to complete the optional preparation while controlling for the choice to compete, `r apa_print(sec_exploratory2)$full_result$genderWoman` (see Figure 2). In fact, even in the condition where participants were forced to prepare for 12 rounds, lasting on average two minutes, there was a significant effect of gender on the choice to prepare, `r apa_print(sec_exploratory3)$full_result$genderWoman`. Here too, we find that participants correctly predicted that women prepared more for the task, `r apa_print(exploratory3d, n= nrow(clean))$statistic`. They also reported that women are more likely to prepare in general, `r apa_print(exploratory3c, n= nrow(clean))$statistic`. Overall, our previous work provides compelling evidence that women are more likely to prepare than men, even after being forced to do so. 
