---
output:
  word_document: default
  html_document: default
---

Competitions are increasingly prevalent in the global labor market [@Lavy2004; @Lemiuex2009] and the winners of competitions are disproportionately rewarded [@Frank2010]. Much work on gender differences in competitiveness has focused on designing interventions that increase women’s willingness to compete. We test the viability of one such intervention in Chapter 1 of this dissertation by providing men and women opportunities to practice before competing. While the intervention ultimately did not increase women's competitiveness, the studies in Chapter 1 revealed that women prepare more than men. Moreover, both men and women believed that women would be more likely to practice. Thus, a new gender difference in preparation was discovered. In the current Chapter, we ask whether competitions themselves disproportionately increase rates of practicing among women, such that women are especially likely to prepare before entering competitive environments relative to non-competitive environments. Additionally, we explore whether gender stereotypes may be driving the gender difference to practice. While considerable efforts have been made to understand why men are more likely than women to choose to compete, less attention has been paid to whether and how men and women may differentially respond to competitions. Yet, understanding downstream consequences of nudging or forcing women into competitions may too help address gender disparities in economic outcomes [@Blau2017; @Altonji1999]. 

## The gender gap in labor market outcomes and preferences for competition

Compensation packages based on performance pay, such as bonuses, commissions, and piece-rate payments, have risen in popularity relative to hourly/salaried pay, especially among workers in the highest tiers of occupations [@Hall1998; @Murphy1999; @Cunat2005; @Lemiuex2009]. There is evidence that the increasing use of performance pay lends itself to wage inequality. @Lemiuex2009 showed that an increased dependence on performance pay during the late 1970’s and early 1990’s accounted for 21% of the observed growth in variance of men's wages. Bonuses and commissions, arguably the most competitive compensation schemes, may be especially important in driving the large disparity between the highest and lowest percentile earners within organizations [@Bell2010; @Bell2014; @Benabou2016]. Importantly, performance pay may contribute to the gender wage gap too. Using data from the National Longitudinal Surveys of Youth, @McGee2015 show that women are less likely to be employed in occupations that receive bonuses, and simultaneously are more likely to receive piece-rate pay – the least competitive of all forms of performance pay, where workers are paid based on their absolute output. 

The gender wage gap refers to the difference in earnings between men and women, with men earning more, on average, than women worldwide. While the gender gap has decreased over the last three decades, the improvements have been modest. For instance, it is estimated that the ratio of women’s to men’s wages in the United States increased to only 67% in 2016 from 53% in 1986 [@Gharehgozli2020]. While numerous factors have been implicated in contributing to the gap, including human capital variables (e.g., gender gaps in education and work experience) [@Goldin2006a], workforce interruptions and fewer hours among women [@Blau2017a], persistent gender segregation by field and occupation [@Blau2017; @Goldin2014], along with discrimination [@Blau2017], some researchers have looked to gender differences in men’s and women’s willingness to compete and to a lesser extent, behavior that results when required to enter a competition. An expanding literature in both psychology and experimental economics suggests that men, compared to women, are more willing to enter competitions. This finding was first documented in a foundational experiment by @Niederle2007, and has since been replicated numerous times across populations [for reviews, see @Croson2009; @Niederle2011, @Niederle2017; and @Shurchkov2018), including among hunter-gatherers [@Apicella2015]. 

Typically, researchers measure competitiveness as one’s willingness to enter a tournament where success and thus, earnings, depend on outperforming (an)other player(s). Participants who prefer tournament payment schemes over piece-rate payment schemes, where payments are solely determined by the number of successfully completed units, are said to be competitive [@Niederle2007]. Importantly, this laboratory measure of competitiveness predicts education and career choices, along with earnings outside the lab [@Buser2014; @Zhang2012; @Buser2017c; @Samek2019; @Berge2015; @Reuben2015; @Reuben2017; @Buser2017b; @Buser2020a], and thus may help explain gender gap in labor market outcomes. 

To date, most of the research on gender differences in competitiveness has focused on i) either explaining the sources of the gender difference – for instance, men tend to be more confident and risk-seeking than women [e.g., @Veldhuizen2017] or ii) designing interventions to encourage women to compete more [@Balafoutas2012; @Sutter2016; @Cassar2016; @Brandts2015; @Niederle2013; @Brandts2015; @Healy2011; @Alan2018]. For instance, @Kessel2021 find that telling participants about the gender difference in willingness to compete as well as the implications on earnings, reduces the gender gap in competitiveness. Crucially, less consideration has been paid to how competitions may differentially, and perhaps negatively, impact women in other ways, such as lowered performance both during and after competition, reduced desire to enter future competitions, or potential opportunity costs related to time spent (over) preparing when required to compete.

The rest of this introduction briefly summarizes the literature on how men and women may differentially respond to competitions at three specific time points (i.e., before, during, and after competition) and highlights the need for more work on how men and women may behave differently *before* entering competitions. Second, we introduce several reasons for why preparation might be one specific behavior where gender differences before competition arise, with the expectation that women practice more than men, especially when competing. Finally, we introduce the current investigation, which experimentally tests whether and how competitions affect gender differences in preparation. 

## Gender differences in response to competitive environments

There are three major time points at which competition may affect men and women differently: before, during, and after competition. The majority of previous studies in this space have examined gender differences in response to competition during and after performance. 

### During competition

Many lines of work have explored the possibility of gender differences in performance under competitive pressure. Here, we summarize the work on different forms of competitive pressure, including studies that explicitly labeling one environment as competitive or, in other cases, impose certain rules or create performance contexts under which, although not explicitly labeled as competitive, reduce an individual's probability of earning a specific reward or reduce the amount of the reward they can earn, and as such, impose competitive pressure. 

Although competitions are generally motivating and designed to improve performance by increasing effort [@Connelly2014a; @Murayama2012; @Miller2019a], previous research suggests that men perform better under competitive payment schemes relative to non-competitive payment schemes, while women's performance does not respond to competitions [@Gneezy2003; @Gneezy2004; @Gunther2010; @Samak2013; @Booth2022; @Gneezy2004; see @Niederle2011 for review; along with @Cotton2013 and @Dreber2011 for exceptions]. @Gneezy2003 show that there is no gender difference in performance when participants are solving mazes following a piece-rate payment scheme, but a significant gender difference in performance arises under a tournament payment scheme, with men performing better. @Gunther2010 replicate the effect of competition on gender differences in performance for a male-typed task, but find no gender differences in performance during competition for female-typed or gender-neutral tasks. 

@Shurchkov2012 finds evidence that two types of pressure may explain part of gender difference in competitiveness: task stereotypes and time constraints. Specifically, they find that women's performance suffers when they compete against others on a male-typed math task with high time pressure (2 minutes to perform), while there are no significant gender differences in performance during competition on a female-typed verbal task with low time pressure (10 minutes to perform). Also, they find that women are significantly more likely to choose to compete when there is low time pressure in a math tournament, while men's competition entry does not significantly vary based on the time pressure treatment.  

There is also field evidence of gender differences in performance during competition. @Paserman2007 show that women's probability of committing costly errors over the course of a tennis match increases at high-pressure moments, while men's probability of committing such errors does not significantly change across the match. 

There is also extensive work on gender differences in performance and effort under competitive pressure within academic contexts [@Iriberri2019; @Cai2019; @Ors2013; @Azmat2016; @Price2008; see @Niederle2010c for a review on gender differences in math tests scores]. For instance, in a study of gender differences in responses to different levels of competitive pressure on a Korean quiz show for student scholarships, researchers find that when stress is kept to a minimum, there are no gender differences in performance, but when certain knock-out rules are applied, a difference emerges [@Booth2021]. @Morin2015 show that effect of education reform that led to a double-cohort, and as such, increased competition for admission at the University of Toronto, increased men's average grades and proportion of men who graduated on time relative to women, driven largely by men increasing their effort after the reform. 

In a study examining performance during the GRE examination, @Attali2012 show that the gender gap in performance is significantly greater under the real GRE, which they demonstrated was driven by men increasing their effort, while women's effort stayed the same. The real GRE is inherently more competitive and higher-stakes than a voluntary experimental section of the GRE, providing further support for gender differences in performance in response to competitive pressure in the field. 

There is also a growing literature showing that women are less willing to guess on exams [@Pekkarinen2015; @Baldiga2014; @Iriberri2021], which in turn negatively impacts their performance on said exams, widening the gender gap in performance under competitive pressure. @Riener2018 shows this phenomenon starts at an early age, with girls as young as eight years of age being significantly less willing to guess on exams relative to men. 

### After competition

During repeated competition, women tend to perform worse in subsequent performance rounds after losing, even if the monetary prize they lost was relatively meager, while men only perform worse in subsequent rounds if they lost the chance to win a large monetary prize [@Gill2014]. Other research suggests women stop competing altogether after losing if given the choice. @Buser2019, who examine the effects of losing while competing in the Dutch Math Olympiad on the choice to compete in subsequent years, show that men are just as likely to compete even if they lost the previous year, while women are less likely to compete again if they lost before. In a separate study, @Buser2016 show that men react to losing during a competition by picking a more challenging target for their subsequent performance while women lower their performance.

Similarly, @Shastry2021 performed an experiment among Economics professors where they received feedback in the form of a letter from the editor on a hypothetical journal submission, with randomized decision outcomes (i.e., revise and resubmit, reject and resubmit, reject). They find that among the assistant professors within the sample, a flat rejection during the review process reduced women's beliefs in their probability of success in the future significantly more than men's - as quantified by their rating of the probability of publishing the paper in the same journal or in any leading journal. This gender gap in confidence does not hold among associate or full professors, which they argue is likely driven by survivorship bias. 

In another study of the effects of feedback on subsequent gender differences in behavior and beliefs, @Coffman2021 examine both the role of task stereotypes (again through a female-typed verbal quiz and a male-typed math quiz) and feedback (positive or negative) on both confidence and choice in a compensation scheme (piece-rate or tournament payment). They find that women's beliefs and choices after negative feedback are updated more negatively than men, regardless of their performance or choices before feedback. Overall, the current body of literature suggests that competitions may differentially impact women and men, both during and after said competitions. 

### Before competition

As mentioned previously, little research has examined how competitions may affect gender differences in behavior during another critical period: before an individual enters a competition, where they have the most control of their subsequent performance in the competition. Given previous research suggesting that women and men may respond differently during and after competitions, we expect that they will also employ different behaviors and have different perceptions of themselves and others in advance of a competition. 

Our research in Chapter 1 suggests that women, compared to men, are more likely to prepare when given the opportunity. While the primary goal of this research was to experimentally test how preparation might influence gender differences in willingness to compete, a significant gender difference emerged in the choice to practice ^[Note: The result was significant in only two of the three experiments conducted. In the experiment where the result was not significant, the women still practiced at a higher rate than men.]. Notably, the gender difference was present regardless of the payment option scheme chosen (i.e., the competitive tournament payment scheme or non-competitive tournament piece-rate payment scheme), though such interaction effects may have been difficult to detect with the sample sizes employed. Moreover, because payment schemes were not randomized there may have been selection effects such that those who were more likely to compete may have also been less likely to prepare. Thus, whether tournament  (relative to piece-rate) payment schemes lead women to prepare disproportionately more than men is still unknown.

#### Does competition elicit a gender difference in preparation?

There are three non-mutually exclusive reasons to suspect that competition would be especially likely to increase women's preparation before performance: the effects of competition on confidence, risk, and/or the stereotype that women prepare more than men.  

##### Confidence, risk, and rates of practicing 

Women may spend more time preparing than men, especially before competitions, in part because they are, on average, less risk-seeking [@Croson2009; @Dohmen2011b; @Eckel2008; @Bertrand2010a; @Shurchkov2018] and confident [@Bertrand2010; @Lundeberg1994; @Mobius2011; @Barber2001; @Croson2009; @Shurchkov2018, but see @Bandiera2022] than men. Indeed, both confidence and risk attitude have been implicated in driving the gender gap in willingness to compete [@Veldhuizen2017; @Gillen2019; see @Niederle2011 for review]. The extent to which confidence and risk attitude account for the gender gap in willingness to compete is debated; some research suggests that competitiveness may be entirely explained by confidence and risk [@Veldhuizen2017; @Gillen2019] while other research suggests that there remains a residual gap in the choice to compete [@Niederle2007]. Regardless of whether competitiveness is a stand-alone trait, confidence and risk attitude may lead to differences in how men and women react to competitions, possibly including the decision to prepare before competitions.

Preparing for a competition, through either practicing or studying, may be a strategy individuals employ before entering a competition. Since competitions, by definition, compare the performance among two or more individuals, they naturally lead to self-evaluation and comparative judgments of self with others - processes that are intimately linked to confidence. Thus, less confident individuals may prepare more in order to reduce the negative feelings caused by low confidence independent of any ambitions to win, since mastery is an important driver of confidence [@Gist1992; @Usher2008]. Given the aforementioned evidence that women tend to be less (over)confident than men [@Mobius2011; @Niederle2011; @Croson2009; @Lundeberg1994; @Niederle2007; @Bertrand2010a; @Beyer1990; @Beyer1997], we may expect to see women preparing more than men, particularly in competitive contexts, which, again, naturally invoke self-other assessments. 

Importantly, on top of their possible effects on preparation through confidence, competitions may also cause individuals who are more risk-averse to prepare more. Risk attitudes, as shown in Chapter 1, reflect the preference for a certain gain over a gamble, even if the gamble has an equal or greater monetary expectation [@Kahneman1982]. Since competitions, by definition, reduce the probability of earning the prize of said competition, even if the expected value of one's earnings is equal to non-competitive payment schemes, competitive payment schemes are inherently more risky relative to non-competitive payment schemes. Thus, it is possible that the aforementioned gender differences in risk attitudes [@Bertrand2010a; @Croson2009] may also lead women to be more likely to prepare before performing in a competition relative to men. 


#### Gender stereotypes and practicing  

Gender differences in preparing may be driven by persistent stereotypes of men and women's tendencies to prepare more before performance. Gender stereotypes derive from observers' automatic tendency to make correspondent inferences about men and women's dispositions [@Gilbert1995; @Ross1977; @Jones1967; @Gawronski2004], a process that appears to affect perceptions of others as early as two years of age [@Poulin-Dubois2002; @Serbin2002]. Stereotypes involve prescriptive, proscriptive, and descriptive components [@Prentice2002], where prescriptive and proscriptive stereotypes reflect cognitive representations of the characteristics women and men should and should not have, respectively, while descriptive stereotypes are representations of the typical man and woman [@Burgess1999]. Gender stereotypes can encompass a variety of attributes, including physical (e.g., women are dainty), cognitive (e.g., men are analytical), and personality-based (e.g., women are nurturing) stereotypes [@Cejka1999; @Deaux1984].

Indeed, there is extensive evidence that gender stereotypes affect one's beliefs about themselves and their performance, along with one's behavior, such that behavior aligns more closely with gender stereotypes. For instance, @Bordalo2019 found that individuals tend to overestimate actual performance gaps between genders based on stereotypes, such that women were far less confident in answering questions gender-incongruent domains (e.g., business, math, and sports) than they should have been given their performance. @Coffman2021 further explore how belief updating is affected by positive or negative feedback about one's performance, and show that receiving negative feedback in a gender-incongruent domain leads to a long-lasting negative effect on beliefs about performance (a week later), while negative feedback in gender-congruent domains does have such lasting effects. @Coffman2019 show similar effects, such that individuals tended to update their beliefs more in concordance with gender stereotypes, such that both men and women who receive positive feedback about their performance adjust their beliefs significantly more in line with gender stereotypes in gender-congruent domains than in gender-incongruent domains. 

There is direct evidence that these beliefs can affect subsequent behavior and performance. For instance, @Bian2017 show that the gender stereotype that men tend to succeed in activities and fields that require brilliance leads girls as young as 6 years of age to avoid activities that supposedly require brilliance. Within the field, @Guiso2008 find that the gender gap in math, in which boys typically outperform girls on math tests, disappears in more gender-equal societies, as measured through the World Economic Forum’s Gender Gap Index, which captures the opportunities, education, and well-being of women within a given country. Similarly, @Breda2020 measure the stereotype that "math is not for girls" among students across 64 countries, and find that countries in which a larger proportion of students held this belief tended to have fewer women represented in math-intensive fields. Individuals are also less likely to engage in self-promotion behaviors in gender-incongruent domains. For instance, @Coffman2014 show that both men and women are less likely to contribute ideas to a group decision in gender-incongruent decision-making domains (e.g., women contributing ideas to a decision in the domain of sports), even when the group would have made a better decision with their contribution. On the other hand, @Coffman2021a find that people are less likely to promote themselves when they are the gender minority in their group, presumably because they prefer to conform with perceived gender norms. Finally, @Niederle2011 reviews an extensive literature showing that gender differences in competitiveness can be changed based on task type (usually male-typed math or female-typed verbal tasks), suggesting that stereotypes about the ability of one's gender to perform on a task affects willingness to compete. Overall, research across fields shows that gender stereotypes affects gender differences in beliefs, performance, and behaviors.

We found in Chapter 1 that women not only prepared more than men, but that participants also correctly predicted that women would prepare more than men, suggesting that there are gender stereotypes about preparation in favor of women. Across three studies participants were monetarily incentivized to correctly guess which gender would choose to prepare for the paid multiplication task, such that their responses were unlikely influenced by desire to respond in a socially desirable way. Most participants in the three studies (Study 1: 83.37%, Study 2: 80.95%, Study 3: 56.7%) correctly predicted that women would practice more than men before performance on the multiplication task used in the studies and in general (Study 1: 89.51%, Study 2: 85.38% and Study 3: 59.5%) ^[Note: The questions about general gender differences in willingness to prepare were not incentivized, as we could not directly attest to their accuracy. Also, part of the reason the percentages for Study 3 are lower than for the other studies is because participants were given the option to say there were no differences in gender preparation behaviors]. 

Given our evidence gender stereotypes about preparation, in combination with the evidence that gender stereotypes in general affect subsequent behavior to align with said stereotypes, it is entirely possible that gender stereotypes drive women’s tendency to prepare more than men. 

Gender stereotypes about competitiveness in combination with gender stereotypes about preparation might also affect women’s preparation behaviors. That is, when women are forced to compete and are offered the opportunity to prepare before the competition, this would likely activate thoughts about gender stereotypes for both of those behaviors - that is, they will likely ask themselves 1) how typical is it for my gender to prepare? and 2) how typical is it for my gender to compete and/or perform well under competitive pressure? That is, if there’s a general belief that women prepare more than men (for which we find evidence in Chapter 1), but do not choose to compete or perform well under competitive pressure (that is, they are less competitive) (for which we find evidence in Chapter 1) - they might assume that they should prepare more to compensate for the discordance between how competitive they need to be to enter the competition and the typical level of competitiveness perceived in women according to gender stereotypes about competitiveness. 

Overall, given the evidence that gender stereotypes can lead to behavior that aligns with stereotypes specific to one's gender, we expect that participants' perceptions of gender differences in preparation likely contribute to gender differences in actual preparation behavior, along with their perceptions of how much they prepare relative to others, especially in competitive settings. 

## The current experiment 

Here, we study how women and men differentially respond to competition through preparation. We expect to see both gender differences in actual preparation behavior, along with gender differences in perceptions of relative preparation, especially when men and women are required to compete (relative to non-competitive environments). Specifically, we experimentally test whether competition exacerbates previously established gender differences in preparation by manipulating participants’ assigned payment scheme (i.e., competitive tournament payment scheme or non-competitive piece-rate payment scheme). We hypothesize that women will choose to practice problems at a higher rate than men, especially when assigned to the competitive tournament payment scheme (i.e., we anticipate a main effect of gender on the choice to practice, and an interaction between gender and condition, such that women will practice more than men in both conditions, but the difference-in-differences between practicing rates across genders will be greater in the competition condition). 

While we did not find an interaction between gender and choice to compete on the decision to prepare in Chapter 1, the sample in those studies was likely too small to detect interaction effects. Moreover, participants were not randomized to their payment schemes. As such, selection effects may obscure actual relationships between gender and practicing by payment schemes. The current study expands on the results of in Chapter 1  by directly manipulating participants’ payment scheme and recruiting a sample large enough to detect interaction effects. 

It is also entirely possible that women prepare more than men regardless of the payment scheme, possibly because of gender stereotypes that lead them to think they should prepare in advance of any type of performance, or perhaps because in general, they want to reduce the risk of earning nothing, even in the piece-rate payment scheme. Or, as suggested by the extensive literature showing that women's performance does respond to competitive pressure [cites], women's effort may not differ significantly across different levels of competitive pressure, while men's effort may increase in response to competitive pressure. Thus, we may still find no evidence for an interaction effect between gender and choice to compete in the study in Chapter 2, suggesting that women's preparation behaviors are insensitive to the payment scheme relative to men.  

Not only do the aforementioned factors (i.e., gender differences in confidence and risk attitudes, and/or gender stereotypes likely affect gender differences in preparation behavior, but they likely also affect one's *perceptions* of their relative rate of preparation. For instance, when an individual has less confidence in their ability to perform on a task, they may feel less capable, or in other words, less prepared, relative to others when it comes time to perform on said task. Given the likely effects of competitions on self-other assessments, they increase the likelihood an already less confident individual, who may feel as though they are not as capable as others on performing well without preparation, will suffer these feelings of relatively lower preparation. Similarly, in riskier contexts, such as competitions, an individual who is more risk averse than others may feel as though they are not preparing sufficiently relative to others to reduce the inherent risk of the situation. Finally, it would reason to assume that gender stereotypes drive not only preparation behavior, but perceptions of relative preparation - given the argument that our behavior is driven by perceptions of norms and how we stand relative to the norm.  

For the above reasons, this study included a new measure of how much participants felt they prepared relative to other participants to test whether gender predicts participants' perceptions of their relative amount of preparation. More concretely, we expected women will be more likely to assume they practice less than others compared to men (that is, the effect of gender on perceptions of relative practice will be negative), especially when assigned to the competitive tournament payment scheme (such that women in general will think that they practice less than other participants than men, but this difference will be exacerbated in the competition condition). 

The research design, hypotheses, measures and analyses for this chapter were pre-registered on [OSF](https://osf.io/8bwfz/) and all analyses were conducted in R statistical software (version `r paste0(R.Version()$major,".", R.Version()$minor)`). 
