---
title: "fig_with_notes"
author: "Keana Richards"
output:
  html_document:
    chunk_output_type: console
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '4'
editor_options: 
  chunk_output_type: console
---


```{r, include = F}

knitr::opts_chunk$set(message=FALSE, warning = F)

## limiting number of digits to 2 decimal places
options(digits = 2)
options(repos="https://cran.rstudio.com" )
# load packages -----------------------------------------------------------



if(!require('pacman')) {
  install.packages('pacman')
  }
pacman::p_load(tidyverse, here,summarytools, magrittr, papaja)


options(scipen=999)


```
# Study 1 


## Plot from presentation - grouped by competition choice and gender 

```{r}
# load data ---------------------------------------------------------------

clean <- read_csv(here("study1", "data", "clean.csv"))
```


```{r}
dat <- dplyr::select(clean,gender,comp_choice, condition) %>% group_by(comp_choice, gender) %>%  dplyr::count(gender, comp_choice, condition) %>% mutate(percent = n / sum(n), error = sqrt((percent * (1-percent))/n)) %>% filter(comp_choice == "tournament")


p <- ggplot(data = dat, aes(x = condition, fill = gender)) +
  geom_bar(aes(y = percent*100),
  position = "dodge", stat = "identity") + geom_errorbar(aes(ymin =(percent*100)-(error*100), ymax =(percent*100)+(error*100)), width=.05,
  position=position_dodge(.9)) + 
  geom_text(x = 1.5, y = 100, label = "***") + 
  labs(x = 'Condition', y = 'Percentage Competing') +
  scale_fill_manual(values=c("springgreen3", "slateblue1"),  labels = c("Men", "Women")) + theme_apa() +
  scale_x_discrete(labels = c("Control", "Prepare")) + theme(panel.border  = element_blank()) +
  #draws x and y axis line
  theme(axis.line = element_line(color = 'black'))
p

```


```{r, results = "asis"}
print(stby(list(clean$gender, clean$condition), INDICES = clean$comp_choice, FUN = ctable))
```


## Plot grouped by condition and gender 

```{r}

dat <- dplyr::select(clean,gender,comp_choice, condition) %>% group_by(condition, gender) %>%  dplyr::count(gender, comp_choice, condition) %>% mutate(percent = n / sum(n), error = sqrt((percent * (1-percent))/n)) %>% filter(comp_choice == "tournament")


p <- ggplot(data = dat, aes(x = condition, fill = gender)) +
  geom_bar(aes(y = percent*100),
  position = "dodge", stat = "identity") + geom_errorbar(aes(ymin =(percent*100)-(error*100), ymax =(percent*100)+(error*100)), width=.05,
  position=position_dodge(.9)) + 
  geom_text(x = 1.5, y = 100, label = "***") + 
  labs(x = 'Condition', y = 'Percentage Competing') +
  scale_fill_manual(values=c("springgreen3", "slateblue1"),  labels = c("Men", "Women")) + theme_apa() +
  scale_x_discrete(labels = c("Control", "Prepare")) + theme(panel.border  = element_blank()) +
  #draws x and y axis line
  theme(axis.line = element_line(color = 'black'))
p
```

```{r, results = "asis"}
print(stby(list(clean$gender, clean$comp_choice), INDICES = clean$condition, FUN = ctable))
```

