---
output:
  word_document: default
  html_document: default
---

Gender gaps in economic outcomes persist, despite women's gains in education. Various explanations have been proposed for these persistent gaps, including gender differences in competitiveness. In both lab and field studies, women tend to compete less than men, despite performing just as well. Across three studies in Chapter 1 involving over 3000 participants recruited from Amazon Mechanical Turk, we experimentally test whether variations of preparation (i.e., knowledge of an opportunity to prepare, limited opportunity to prepare, and unlimited opportunity to prepare) before performance reduce gender differences in willingness to compete. We also measure participants' choice to prepare and elicit their beliefs about whether men or women will prepare more. First, we show that the preparation intervention does not increase women's competitiveness across studies. Instead, we discover a novel gender difference in the choice to prepare before performance regardless of one's competitiveness, risk aversion, and confidence.  
\newpage

This finding aligns with participants' incentivized beliefs - the majority of participants correctly predicted that women would practice more than men. Given this novel finding, Chapter 2 experimentally tests whether the gender difference in preparation may be exacerbated in competitive environments relative to non-competitive environments (N = 3980). Although we replicate the gender difference in preparation, we find no evidence that competitions increase preparation in men or women. This means that women prepare more than men regardless of whether they were assigned to compete. Again, this aligns with participants' incentivized beliefs about gender differences in preparation. This dissertation discusses the downstream and potentially negative consequences of interventions designed to get women to compete, such as the one introduced here. It also discusses both the causes and implications of this newly discovered gender difference in preparation. Future research should explore the boundary conditions, moderators, and mediators of the newly discovered gender difference in preparation. Finally, rather than designing interventions that encourage women to compete more, we implore future research to focus on exploring interventions that change the system to be more gender-inclusive.