---
output: word_document
---


## Main hypotheses: 

First, we find that, like previous literature in this space and our own studies across Chapter 1, women are more risk-averse and less confident than men in this study. Yet, even when controlling for gender differences in risk attitudes and confidence, we replicate findings from the studies in Chapter 1 that women choose to prepare more than men. Interestingly, women chose to prepare more regardless of the payment scheme (competitive tournament, non-competitive piece-rate) they were randomly assigned to. Also, although participants overall were more likely to practice in the tournament scheme, we did not find evidence that assignment to either a tournament or piece-rate payment scheme significantly predicted the binary choice to practice problems, after including gender and the interaction between gender and condition in the model. Although we did not explicitly hypothesize a priori that condition would be a significant predictor of the choice to practice, it is nonetheless important to note that gender explains participants' decision to practice problems over and above any effect of condition. 

We also included other means of quantifying preparation (i.e., amount of time spent on the pages with practice problems and study tables, number of practice problems completed, and total number of practice rounds completed) to test the robustness of the gender effect, and find evidence across our multiple measures of preparation that women tended to prepare more than men– they spent more time completing practice problems and studying tables, completed a higher number of practice problems, and completed more rounds of practice. 

One important consideration when interpreting the effect of gender on the choice to prepare before the task is that, contrary to our prior studies (Chapter 1), we find a significant effect of gender on task score, even while controlling for individual differences in risk attitudes and confidence, unlike two out of the three studies in the last chapter. It is possible that shortening the task contributed to this effect - especially considering evidence suggesting that women's performance may suffer under more competitive pressure [cites]. There may be less pressure to perform well during a two-minute task (used in all of the studies of Chapter 1) relative to a 30-second task (used in the study in this Chapter). In support of this possibility, @Shurchkov2012 shows that womens' performance significantly improves, to the extent that they outperform men, in a low time pressure competition. 

We also found evidence for the hypothesized main effect of gender in our other primary pre-registered analysis, where women were more likely to assume they practice less than others compared to men. This effect held when using our pre-registered version of the analysis using the perceived practice deviation variable, representing the accuracy of participants' guess of how much their level of practicing compared to others participants' level of practicing, both among the full set of participants and among the subset of participants that chose to practice. We also wanted to test the robustness of the effect using a slightly different way of quantifying our relationship of interest, where we included participants' raw self-reported practice decile as the main dependent variable of interest (instead of perceived practice decile) with gender and number of practice problems attempted as predictors. We replicate the aforementioned effect, where women tended to think they practice less than others, regardless of how many practice problems they actually attempted - although this effect only held among the full set of participants and not among the subset of participants who chose to practice.  

We did not find the hypothesized interaction between gender and condition on perceived practice deviation - suggesting that, like actual decisions to practice, women's tendency to perceive they are practicing less than others is not significantly affected by whether they are competing or not. Although it is not possible to draw strong conclusions from null effects, we explore possible reasons for the null interaction between gender and condition further in the subsequent general discussion summarizing results across all studies of the dissertation. 

## Perceptions of gender differences in performance, competition, and preparation

With respect to the questions asking participants to indicate their perceptions of gender differences about our main behavioral variables of interest, we replicate findings from all three studies in Chapter 1. Even though participants expected that women and men would not have a significant difference in task scores, they expected men to prefer the tournament payment scheme over the piece-rate payment scheme, while expecting women to both i) prefer the piece-rate payment scheme over the tournament payment scheme and ii) prepare more, both before completing the multiplication task used in this study and in general before most tasks. Again, with the exception of the general gender difference in practice questions, all of the other perception questions were incentivized for accuracy to reduce socially desirable responding. Our exploratory analysis of the new set of questions about perceptions of relative practicing compared to each gender included in the study of this Chapter support these general perceptions of gender differences in preparation. Given the targeted nature of the questions, we were able to test how participants' responses changed based on whether they were asking to compare their level of practicing in the study to only participants that identified as women or only participants that identified as men, and find that participants were significantly more likely to indicate that they practiced less relative to women than relative to men.  

## Summary of takeaways

Overall, our results for the study in Chapter 2 suggest that women prepare more than men, regardless of whether they were assigned to a competitive tournament or non-competitive piece-rate payment scheme, and despite thinking they practice relatively less than men for the multiplication task used in the study. It is possible that gender stereotypes are driving these gender differences in behaviors and perceptions, given our replication of the findings from all three studies in Chapter 1 that participants expected women to prepare more both before the specific task used in the study and in general, along with the finding that participants' tended to rate their relative practicing significantly lower when comparing themselves to women than men.     



