---
title: "discussion"
author: "Keana Richards"
date: "17/3/2022"
output: word_document
---

In this final test of the effects of the opportunity to prepare on the choice to compete, we explored whether having unlimited time to prepare would reduce the gender gap in competitiveness. First, we test whether there is a gender difference in competitiveness, which we do find again within the context of this design. That is, women do indeed compete less than men when gender is included as a predictor by itself in the model - but the fact that the effect disappears when controlling for risk attitudes, confidence, and task scores provides further evidence that competitiveness may not be a stand-alone trait. We also replicate the effects of gender on risk attitudes and confidence. In this study, we do not find evidence of a gender difference in task score when controlling for confidence and risk attitudes, like Study 2. Thus, Study 1 is the only study thus far in the dissertation that has found a gender difference in task scores that does not appear to be explained by gender differences in risk attitudes or confidence. 


#### Summary of main experimental results

Next, we explored the main experimental results for the intervention attempting to reduce the gender difference. We hypothesized that being assigned to the unlimited preparation condition that closely resembled the paid task would lead participants to choose to compete more often than participants who completed the control subtraction task that was not relevant to the paid task. In support of this assumption, when asked which condition they thought would be most helpful for improving performance on the multiplication task during the manipulation check, participants resoundingly chose the preparation condition over the control condition. Participants' responses on the manipulation check aligned with their choices to prepare across conditions, such that participants in the unlimited preparation condition were significantly more likely to choose to study and practice relative to participants in the control condition. Overall, we have evidence that the subtraction task was an appropriate choice for the control condition, as participants thought that it would be less likely to help their performance on the paid task relative to the multiplication task. Despite both behavioral and self-report evidence that participants thought the unlimited preparation condition would be more helpful for performance, we did not find evidence that condition assignment affected participants' choices to compete. Yet again, contrary to our hypothesis of an interaction between gender and condition, the effect of the unlimited opportunity to prepare before completing the paid task did not differ by gender. 

#### Gender differences in preparation

Like the previous studies, the gender difference in preparation was also an important part of our analyses. Yet, in this study we do not find evidence of a gender difference in the choice to prepare. There are a few possible reasons we did not replicate the effect of gender on the choice to prepare. The discrepancy could be explained by the lower number of participants in the preparation condition relative to previous studies given the random assignment to condition. For this reason, we may have had less power in estimating the effects of gender on the choice to prepare. It is also possible that differences in the design of this study relative to the previous two studies drove the differences, which will be further explored in the overall discussion section.   

In this study, we changed the nature of preparation - such that we had the novel opportunity to explore different ways of measuring preparation, including the choice to study multiplication tables and the amount of time a participant spends studying multiplication tables. With these new measures, we find that, among participants who chose to study the tables, women spend more time on the page (presumably studying, although we cannot directly attest to that, given the online nature of the experiment), though they did not choose to study at significantly higher rates than men. Thus, we have mixed evidence based on these new measures that women prepare more than men.  

#### Perceptions of gender differences in preparation, performance, and competitiveness

Like the previous two studies in this dissertation, we explored participants' perceptions of gender differences to see whether there tends to be consistency in beliefs about gender differences in performance on the multiplication task, along with gender differences in the choice to prepare and compete, and if so, whether these beliefs aligned with the actual results found. Importantly, participants were again incentivized to guess the study results correctly to reduce the likelihood that participants would respond in a socially desirable way. 

Notably, we added a third response option to the measures in this study, such that participants could indicate that they did not expect a gender difference in a given behavior. The third response option served as a test of robustness, since one could argue that the two-response option measures used in previous studies force participants to choose between indicating men or women when they would have otherwise indicated there was no gender difference in a given behavior.

Yet, contrary to that argument, the results mirror results found in previous studies, suggesting that there are consistent beliefs about gender differences in competitiveness and preparation, despite the consistency in beliefs about a *lack* of gender differences in performance. 

Like the previous studies, we also explored whether these perceptions are aligned with individuals' practicing behavior. However, we do not find evidence that women's preparation behaviors were related to their beliefs about gender differences in preparation. It is entirely possible that the smaller proportion of participants that even had the opportunity to prepare in this study (per random assignment of preparation condition) did not provide sufficient power to test the interaction effect. In fact, out of the sample of participants in the preparation condition, only a total of 136 participants agreed to prepare, which may be too small of a sample to detect the interaction effect. 

#### Summary 

Overall, we find from Study 3 of Chapter 1 that our manipulation of the unlimited opportunity to prepare did not reduce the gender difference in competitiveness. Like Studies 1 and 2, we show that the gender difference in competitiveness itself is explained by gender differences in risk attitudes and confidence. However, we do not replicate the effect that women chose to prepare more than men. Even still, participants believed that women prepared more than men both in general and on the multiplication task, even after we added a third response option where participants could indicate there were no gender differences in preparation. We do not find evidence that women's preparation behaviors are related to their perceptions of gender differences in preparation, though we argue that we may have not had enough power for testing the interaction effect in the current study.

