---
output:
  bookdown::word_document2: default
  bookdown::html_document2: default
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
documentclass: book
---

# Introduction {.unnumbered}

```{=tex}
\adjustmtc
\markboth{Introduction}{}
```

Women's labor force participation has increased exponentially over the past several decades [@Goldin2006a; @Statistics2020], rising from 32% to 57% between 1960 and 2018 (where women here are defined as 16 years or older) [@Statistics2020; @Blau2017; @Eagly2019], while men's participation has decreased over the same period (from 82% to 69%). As a result, the gender gap in labor force participation fell to a 12% difference. Additionally, women have been increasingly entering previously male-dominated occupations [@Blau2013; @Reskin2009; @England2010].

Despite progress towards gender equality (e.g., women's suffrage, a reversal of the gender education gap, women's increased participation in the labor market) [@Goldin2014; @Goldin2006a; @Goldin2006; @Blau2010; @Blau2013; @Blau2014; @Bianchi2012; @Sayer2005], gender gaps in the labor market persist [@Blau2017; @Goldin2014; @Hegewisch2014; @Bertrand2001; @Blau2014; @Levanon2016; @Blau2006b; @Blau2006a]. One of the most highly cited and tangible metrics for gender disparities in the labor market is the gender wage gap [@Blau2000; @Blau2017; @Nyhus2012; @McGee2015; @Goldin2014; @Hegewisch2014; @Bertrand2001; @Blau2006b]. Recent unadjusted estimates suggest women earn only 79.3% of what men earn [@Blau2017]. 

In the past, gender gaps in education and full-time labor market experience explained a large proportion of the gender wage gap (i.e., 27% in 1980) [@Blau2017]. As women's education and labor force experience has increased over time [@Goldin2006a], the impact of these variables on the gender wage gap has decreased (e.g., 8% in 2010) [@Blau2017]. Since there has been a slowing convergence of the wage gap in recent years [@Blau2006b], identifying and understanding the factors that perpetuate gender differences in labor market outcomes, such as the persistent gender wage gap, is crucial for achieving gender equality in the long-term. 

One area that has been explored extensively within the economics literature is gender differences in competitiveness, both in terms of the choice to compete [for review, see @Niederle2011; @Niederle2017a], to a lesser extent, response to competitions (e.g., performance during competition) [@Gneezy2003; @Gneezy2004; @Gunther2010; @Samak2013]. These studies typically find that women choose to compete less than men, and that they tend to respond less to competition (that is, their performance does not significantly increase to the extent that men's performance does in competitive contexts). Research suggests these gender differences in competitiveness may have implications for real-world economic outcomes [@Buser2014; @Zhang2012; @Buser2017c; @Buser2017b; @Samek2019; @Berge2015; @Reuben2015; @Reuben2017]. For instance, @Buser2014 show that the typical measure of competitiveness used in the lab explains about 20% of gender differences in the choice in an academic track for students entering high school. On the other hand, @Reuben2015 show that gender differences in competitiveness explain about 10% of gender differences in earnings among MBA graduates. Considering these findings, researchers began exploring interventions to increase competitiveness, including enacting gender quotas [@Niederle2013; @Sutter2016], replacing other-competition (i.e., competing against performance of other individuals) with self-competition (i.e., competing against one's previous performance) [@Bonte2018; @Carpenter2018; @Klinowski2019; @Apicella2017a; @Apicella2020], and relaxing pressure during competitions [@Shurchkov2012], among many others [see @Niederle2017a for a review]. We expected that preparation may serve as a viable intervention for increasing women's competitiveness (i.e., choice to compete), since preparation may increase confidence in one's performance and/or reduce perceptions of risk of competition entry, factors that have been well-established as contributors to the gender gap in competitiveness [@Niederle2011], if not factors that fully explain the gender gap [@Veldhuizen2017; @Gillen2019]. 

Thus, it is possible that giving people the chance to prepare would reduce gender disparities in competition. On the other hand, opportunities to prepare might also result in opportunity costs for women, such that women might end up preparing more than necessary before performing. Since prior interventions have not tested the effects of offering individuals the opportunity to prepare before entering a competition, we address this gap in the literature on gender differences in competitiveness through a series of experiments in Chapter 1 where we offer participants variations of the opportunity to prepare (i.e., knowledge of preparation, limited opportunity to prepare, and unlimited opportunity to prepare). We test whether the gender gap in competitiveness is eliminated in the preparation conditions relative to the control conditions. Our research in Chapter 1 also had the explicit goal of identifying whether there are any gender differences in preparation, since any observed gender differences in the tendency to (over)prepare could create opportunity costs for those who choose to prepare. Given the well-established gender differences in risk attitudes and confidence, we reasoned that they might contribute to differences in the desire to prepare before performance. Results from Chapter 1 showed that there are in fact gender differences in preparation, though we did not find gender differences in competitiveness after controlling for gender differences in risk attitudes and confidence. Given these intriguing and novel results, the experiment in Chapter 2 tests whether the gender difference in preparation would be exacerbated in competitive settings, such that women would be especially likely to prepare before entering a competitive, relative to non-competitive, setting. Chapter 2 also seeks to understand the gender difference in preparation further by exploring whether women are more likely to perceive that they prepare less than others relative to men, especially in competitive settings. Overall, these findings have implications for the literature on gender differences in competitiveness and also contribute more generally to our understanding of how interventions intended to reduce gender differences may have negative downstream consequences (e.g., potential opportunity costs of (over)preparing). In addition, we discover a novel gender difference in preparation, which we encourage future research to explore further. 