---
output:
  bookdown::word_document2: default
  bookdown::html_document2: default
  bookdown::pdf_document2:
    template: templates/brief_template.tex
    citation_package: biblatex
documentclass: book
---


# Discussion {.unnumbered}

```{=tex}
\adjustmtc
\markboth{Introduction}{}
```


## Overview of the goals of the dissertation and the main experimental results

### Goals of dissertation 

Previous research suggests that women tend to be more risk-averse [@Croson2009; @Dohmen2011b; @Eckel2008; @Bertrand2010a] and less confident [@Bertrand2010; @Lundeberg1994; @Mobius2011; @Barber2001; @Croson2009], which contributes (at least in part) to gender differences in the decision to enter competitions, and in turn, gender differences in earnings. Since confidence and risk attitudes may be affected by the opportunity to prepare, women may be more likely to compete when they have the opportunity to prepare before entering a competition. Through three experiments in Chapter 1, we experimentally tested whether the opportunity to prepare affects gender differences in competitiveness using three operationalizations of preparation (i.e., knowledge of preparation, limited opportunity to prepare, and unlimited opportunity to prepare). The focus on preparation as the main manipulation was motivated in part by previous research suggesting that women may be more inclined to compete when they are able to engage in self-competition (cite), and thus, may be especially motivated by being able to improve upon previous performance. Based on this possibility, we hypothesized that preparation may be a route by which women can actively see improvement in performance, and thereby, may be more competitive when offered the opportunity to prepare before competing. We also were interested in exploring the possibility that, perhaps driven by gender differences in confidence and risk attitudes, women may prepare more than men in general. The hypothesis that women prepare more than men in general also aligns with recent evidence that fields with lower representations of women tend to be fields that value brilliance, rather than hard work (Cites), which in turn, as shown experimentally, deters women from entering said fields. Thus, across all studies in Chapter 1, we also explored whether there are gender differences in tendencies to prepare. Given the evidence across two out of three studies in Chapter 1 that women tend to prepare more than men, the study in Chapter 2 experimentally tests whether the effect of gender on preparation is exacerbated when participants are required to compete. We also measure participants' perceptions of their relative practicing, with the hypothesis that there may be gender differences in not only participants' preparation behaviors, but also their perceptions of their own preparation behaviors, such that women would be especially inclined to think they prepare less than others, relative to men, and this gender difference in perceptions may be exacerbated in competitive environments.  

### Summary of main results across studies  

Here, we highlight the main findings that we replicate across studies, along with some study-specific findings. By using many of the same questions across studies we are able to test the robustness of our effects through replication, which has been proposed as an alternative with more benefits and fewer costs for researchers when compared to pre-analysis plans alone, with the exception of specific cases (e.g., expensive fieldwork) [@Coffman2015]. In fact, @Coffman2015 show that pre-analysis plans do not always significantly decrease the false positive rate, and instead propose that researchers should place a higher priority on attempting to replicating previous results, which are far less susceptible to false positives even in the face of researcher bias (within at least three to five replications) and for which pre-analysis plans can serve as an exceptional guide to the replication process. @Banerjee2020 proposes a different approach to address some of the drawbacks of pre-analysis plans, where researchers include a publicly available document separate from the main results included in the final paper highlighting results from tests specified in the pre-analysis, which we include in the Appendix (see "Pre-registered analyses"). 

#### Effects of preparation conditions in Chapter 1 on gender differences in the choice to compete  

Across all three studies in Chapter 1, we do not find evidence that preparation increases men or women’s willingness to compete, despite finding evidence in Study 3 of Chapter 1 that participants believe practicing helps performance on the main task both based on their behavior and their responses to the manipulation check question. Thus, we do not find evidence that any forms of preparation used in the studies of Chapter 1 would serve as a viable intervention to increase women’s competitiveness. 

#### Does gender predict preparation? And tests of robustness of gender effect 

Despite the lack of evidence for the effect of preparation on gender differences in the choice to compete, we discovered a sizable gender difference in preparation across multiple measures of preparation, where we find that women choose to prepare more often than men in three out of the four studies in the dissertation. Interestingly, we do not find evidence across any of the studies that the gender difference in preparation varies based on whether participants are competing, either by choice (Chapter 1 studies) or random assignment (Chapter 2 study) - that is, there is not significant interaction between gender and the payment scheme participants were following on their choice to prepare across any of the studies. However, we find that being in a competitive environment by itself (whether by choice or not) reliably predicts the decision to prepare. 

This effect is most robust with the measure of preparation representing the choice to prepare before knowing what the preparation entails, which was the most consistent measure of preparation used across all four studies of the dissertation. Importantly, the observed gender differences in the choice to practice are not explained by gender differences in risk, confidence, or task scores. Finding the effect of gender on the decision to prepare is especially noteworthy because we are drawing from a participant pool (MTurk) where participants could be earning money for their participation through a nearly limitless supply of other studies, so the opportunity costs of preparing may be greater for MTurkers relative to other participant populations, suggesting that this effect could be even stronger when the opportunity costs are lower.

Another measure of preparation used across studies (though measured in slightly different ways based on study design) was the number of extra practice rounds completed, a variable that was constructed to conceptually represent the decision to continue practicing even after having seen what the practicing entails. With this measure, we again find consistent evidence that participants in competitive environments complete more extra practice rounds. In half of the studies, we find evidence that women prepare more using this measure (i.e., Study 1 of Chapter 1 and the study in Chapter 2) and that there is an interaction effect (i.e., Studies 1 and 3 of Chapter 1), but these two possible effects would need to be explored in future research given they do not replicate in the majority of the studies here. 

Importantly, across two out of the four studies, we find no gender difference in task performance when controlling for gender differences in risk and confidence, so the gender difference in the decision to prepare does not seem to be consistently driven by gender differences in the actual need to practice. In the Chapter 2 study, where we find a gender difference in performance on the multiplication task, we argue that one possible reason we find the gender difference was the use of a shortened task (30 seconds instead of two minutes), given previous research suggesting that gender differences in performance emerge under time pressure (Cites). Future research should explore how much preparation is affected by gender stereotypes about the task - such that women may be especially likely to prepare before a male-typed task (e.g., math task) instead of a female-typed task (e.g., verbal task) or generally in settings where they may be susceptible to stereotype threat affecting performance (cites), especially in light of findings that gender differences in performance and decision-making vary based on whether gender stereotypes are prominent in a given context (cites - see NSF - Ctrl + F = "female-typed").

##### Possible reasons for Study 3 deviation 

Notably, we do not replicate the effect of gender on the choice to practice problems in Study 3 of Chapter 1. Although we cannot be completely certain what may be underlying our inability to replicate the effect found in the other studies of the dissertation, we describe a few possible explanations here. First, all other studies in the dissertation measured the decision to complete practice problems *after* participants chose to (or in the case of the study in Chapter 2, were randomly assigned to) compete, while Study 3 measured the decision to practice problems *before* the decision to compete, as necessitated by the main manipulation within the study. Thus, the differences in the results across studies could be explained by the effects of the decision to compete on the choice to practice that are not captured in Study 3. In other words, not knowing they might not have to compete could have reduced motivation to practice. There are also fewer participants that are offered the opportunity to practice in Study 3 (N = INSERT) relative to Study 1 of Chapter 1 (N = INSERT), Study 2 of Chapter 1 (N = INSERT), or the study in Chapter 2 (N = INSERT), again by nature of the study design (i.e., manipulating unlimited opportunity to prepare) so Study 3 likely had less power to detect the effect than the other studies. Finally, the structure of practicing itself varied across the three studies. For instance, the other studies in the dissertation did not offer participants the opportunity to study multiplication tables as a separate decision from the choice to practice problems, whereas in Study 3 of Chapter 1, participants were first asked whether they would like to study multiplication tables, *then* afterwards were asked whether they would like to practice problems. Perhaps being asked whether they would like to study before being asked whether they would like to practice problems reduced participants' interest in completing practice problems. 

#### Summary of effects of perceptions of gender differences

On top of the gender differences in preparation observed, we find that participants *believe* that women prepare more, both in general and on the multiplication task (incentivized for accuracy) across all four studies, while consistently saying women tend to compete less than men (incentivized for accuracy) and they perform just as well on the task as men (incentivized for accuracy). Thus, participants accurately predicted the observed gender differences in preparation, suggesting that they observe these gender differences in preparation directly in their own lives and/or have learned about stereotypes surrounding gender differences in preparation. There is extensive work suggesting that beliefs about identity-based behavior and social norms affect subsequent behavior [@Babcock2012; @Bowles2007; @Toosi2019; @Smith2014; @Benjamin2010c; @Bertrand2015; @Akerlof2000]. If future work confirms our hypothesis that these beliefs may indirectly make women feel like they are expected to prepare more, and as a result, may be overpreparing (relative to their actual skill level) before performing, it would be important to consider interventions that focus on changing beliefs about gender differences in preparation, perhaps by changing norms [@Miller2016; insert other cites], which has been shown to be an effective strategy for affecting subsequent behavior.

There is an emphasis on the importance of work ethic for success in school and work among Black Americans as suggested by the well-known quote "you have to work twice as hard to get half as far," along with experimental evidence suggesting that the sentiment reflects lived experiences of Black Americans [@Desante2013]. Here, we have evidence that belief may also be applied to women, to the extent that the majority of participants across all studies agreed that women prepare more in general, even when they were not incentivized to be accurate in their responses and when they expected that there would be no gender difference in performance. The robustness of this effect across studies and without incentivizing participants' responses about general gender differences in preparation suggest it is a relatively ingrained belief among the general population. 

#### Summarizing effects that relate to previous literature on gender differences 

Our results also speak to previous literature on gender differences in competitiveness, risk attitudes, and confidence. First, we replicate the effect of gender on the choice to compete when gender is included as the only predictor in the model. In other words, women across the studies chose to compete less than men. However, the gender difference in the choice to compete goes away when controlling for task score, risk, and confidence across all three studies, suggesting that the effect of gender may be explained by other factors. Though the gender difference in competitiveness goes away when controlling for other predictors, we find evidence that gender consistently predicts risk and confidence across studies, replicating previous effects found within the literature [@Croson2009; @Dohmen2011b; @Eckel2008; @Bertrand2010a; @Bertrand2010; @Lundeberg1994; @Mobius2011; @Barber2001]. 

## Implications of findings in light of previous research and novel contributions of the dissertation 

When considered in general, the results of this research suggest that women prepare more than men before performing, despite competing at similar rates as men (either through random assignment or by choice) and performing as well as men in half of the studies. And the novel gender difference in preparation discovered in this study aligns with participants' beliefs about gender differences, suggesting that stereotypes may be contributing to gender differences, both in preparation observed in this study and competitiveness observed in the literature, especially given the powerful effects of stereotypes and beliefs about identity-based behavior on one's own behavior (cites). Importantly, opportunities to prepare (in various forms) do *not* affect women's willingness to compete. 

### Main contribution of experiments - new gender diff in prep & possible mechanisms 

#### Describing previous literature with similar effects 

To our knowledge, these studies are the first to demonstrate a gender difference in preparation among adults who must explicitly opt into preparation. However, previous findings within educational contexts have found that women are more likely than men to value dedication and mastery [@Leslie2015; @Kenney-Benson2006], emphasize the importance of hard work [@Mccrea2008; @Hirt2009; @Mccrea2008a], and spend more time preparing than men for an intellectual evaluation when they were told that practice improved future performance [@Kimble2005]. For instance, in a study examining school-aged children’s approach to learning math, researchers found that girls, compared to boys, reported being more motivated to “master” their schoolwork and engage in more effortful learning strategies [@Kenney-Benson2006]. In one study looking at whether delaying competition affects gender differences in the willingness to compete while providing opportunity to study, @Charness2021 did not find a significant difference in the choice to prepare (*N* = 202). Although it is worth noting that, though the effect is non-significant, women are directionally more likely to prepare in their study. Since studying gender differences in the choice to prepare was not one of the main foci of their research, contrary to ours, it is entirely possible they did not have sufficient power to detect the effect of gender on the choice to prepare as a result. 

#### Possible explanations for the gender difference in preparation

The gender difference in preparation observed in the majority of the studies here may be driven by women's relatively greater desire to reduce uncertainty around their future performance (given their greater average risk aversion) and/or increase their performance (given their lower average confidence). Indeed, mastery is an important driver of confidence [for review, see @Gist1992; @Usher2008]. While it is possible that confidence and risk attitudes may be driving the gender difference in preparation, it is important to note that preparation in our studies did not increase competitiveness in either men or women. Because participants were able to choose to prepare across studies before they completed the measures of risk attitudes and confidence, we are unable to identify whether preparation causally affected confidence and/or risk attitudes. Future work should examine the bidirectional relationships between confidence and preparation and risk and preparation.  Of course, other explanations for the gender differences in preparation may also exist, including relative differences in real or perceived opportunity costs, how rewarding it is to prepare, and/or enjoyment on the task, and we encourage future work to explore these alternative explanations. Notably, given the consistency of perceptions of gender differences in preparation found across studies, our results directly speak to another possible explanation for the observed gender difference in preparation: stereotypes that women prepare more than men in general. 


### Contribution to the literature on gender differences in competitiveness, risk attitudes, and confidence 

On top of the discovery of the gender difference in preparation, this set of studies also contributes to the general literature on competitiveness and gender differences in behavior and perceptions. First, we find that, relative to many previous research in laboratory settings, there are a smaller proportion of participants that chose to compete overall. We hypothesize that one factor contributing to this discrepancy is the online nature of the competitions used in this study relative to previous studies, which were largely conducted in person. In fact, @Apicella2017a performs online and laboratory experiments of the same design and finds that more participants (48%; 37.5% women and 57.7% men) choose to compete under the traditional competition design in the laboratory setting relative to the proportion of participants (34.3%; 27.8% women and 40% men) that choose to compete in the online version of the experiment (see Table 1 Percentage Choosing Tournament Rate, by Treatment and Gender). Using the same online task as @Apicella2017a, @Charness2021 find that only 27% of men and 28% of women chose to compete in their study. Thus, our research, in combination with the small set of studies that also test gender differences in competitiveness online, may provide insight into environmental characteristics that may increase (in-person, synchronous competition) or decrease (online, asynchronous competition) an individual's competitiveness. Given the effects of the COVID-19 pandemic on the nature of work, both in the short-term and long-term, future research should explore this possibility experimentally.   

In line with recent research attempting to determine whether competitiveness is a stand-alone trait or is fully explained by other factors (e.g., confidence or risk attitudes), we find that the effect of gender of the choice to compete is no longer significant when risk and confidence are included in the model. Thus, our work would suggest that competitiveness is not a stand-alone trait, and instead gender differences in risk attitudes and confidence are underlying the observed gender difference in competitiveness. In line with this possibility, we find robust gender differences in risk attitudes and confidence across all of the studies in this dissertation. 

### Implications for interventions on competitiveness/Potential drawbacks of competition in the workplace

Our research also has important implications for understanding how to shape interventions in a way that is more gender-inclusive. Much of the research on gender differences in competitiveness has focused on designing interventions that increase women’s willingness to compete. Less work has paid attention to the downstream consequences of said interventions for men and women. Our studies directly speak to the possible consequences of said interventions: in testing an intervention to reduce gender differences in competitiveness, we do not find that competition changed women's preparation behaviors substantially, and in fact, we uncover a gender difference in preparation, suggesting that, when given the opportunity, women may spend more time preparing on average than men, and possibly overprepare. If true, this would challenge prevailing views that gender differences in labor market outcomes could be reduced or eliminated by simple interventions, and in fact, these interventions may actually negatively impact women. Indeed, there are opportunity costs to (over)preparing, including both economic and social costs, such as lost time with family and friends and missed advancement opportunities.

Relatedly, if women *expect* that they will prepare more in competitive environments, this may, in turn, impact whether they even enter competitive environments. Thus, while the studies in our dissertation suggest that merely giving women more time to prepare does not make them more willing to compete (Chapter 1), anticipated effort could still influence labor market outcomes by affecting women’s decisions to enter certain fields or compete for promotions, for instance. In our studies, we use relatively unimportant tasks that are unlikely to greatly impact one’s earnings. Yet, our work shows a gender difference in preparation, suggesting that our study likely *underestimates* gender differences in choices to prepare for tasks that are more important for one’s career and economic prospects. In this way, our study is providing a conservative test of the gender differences in effort and preparation in the real world. 

Although there is evidence that competition in the workplace may increase performance [cites], it is important to consider the potential costs of having an exceedingly competitive workplace, especially considering the evidence that competitive workplaces may elicit high stress responses [cites] and long-term stress has severely negative effects on productivity and health [cites]. 

This observation leads us to the question: is focusing on competitiveness the best approach for improving academic and/or workplace happiness and productivity? Or instead of focusing on forcing individuals across society to accommodate to competitive environments, we make the competitive environments more inclusive of people from all backgrounds and with diverse preferences? Perhaps instead of focusing on other-competition, research should focus more on cooperation [@Gagliarducci2022, insert others] or on self-competition [insert apicella and other cites], assuming these settings do not cause stress or have other negative consequences in their own right, which would need to be tested experimentally. 

The findings from this study also have implications for interventions that focus on individual-level, rather than system-level, institutional approaches. We show that the preparation intervention focused on encouraging women to compete, rather than changing the nature of competition or eliminating competition altogether, had no effect on women's competitiveness. Based on the results from these set of studies and previous research [cites], we recommend future research explore the concept of changing the system, rather than changing women (see https://www.nber.org/system/files/working_papers/w26345/w26345.pdf conclusion section for more cites on changing the system approaches). 

There is strong evidence that these change-the-system measures to increasing gender equality in the workplace are effective. For instance, @He2021 show that women are more likely to compete when the default is to enter a competition, again suggesting that norms may be an incredibly important driver of behavior [also see @Erkal2018]. 

@Niederle2013 shows that requiring a certain number of women be represented among winners of a competition, that is, introducing a gender quota in competitions, significantly increases the proportion of women that choose to enter competitions, and contrary to potential criticisms of quotas, does not decrease overall performance among the winners of said competitions. An additional benefit of gender quotas is that they can reduce bias by increasing exposure to role models, an intervention that has been shown to encourage more women to enter environments that they would otherwise be hesitant or unlikely to enter [@Busso2021; insert other cites]. Thus, quotas likely initiate a positive feedback cycle, where increasing the number of women in a given context increases the likelihood that other women will enter that environment.

## Considerations of this research 

There are a few considerations that must be taken into account when interpreting our findings. First, we only included two genders in our study - participants who identified as men and women - so we are not able to attest to whether any of the results found across studies hold in other genders. We propose future research attempts to address this drawback by actively recruiting participants with a diverse set of gender identities. 

Also, we used the same study population across all studies: participants recruited through Amazon Mechanical Turk. Although this population has been shown to provide results that closely resemble other participant populations (cite) and we took different measures to ensure high data quality across the studies (e.g., excluding duplicate IP addresses, including only CloudResearch approved participants that must pass screening tests, using Qualtrics' fraud detection software to exclude potentially suspicious/fraudulent responses), it is still entirely possible that the data from these studies do not generalize to other participant populations. Future research should attempt to replicate these results in other populations. 

Another unique characteristic of the study is that we employed a simple multiplication task as the main task participants were paid for. Although we originally chose the multiplication task because we predicted that, unlike other tasks, participants can easily see their improvement on the task as they practice, a drawback is that the task is not representative of tasks that are typically used in organizational contexts. Thus, some of the decisions participants made before and after completing the task may not be reflective of decisions made on tasks that may be more relevant in organizational contexts. For that reason, we encourage subsequent research to explore these effects using other, possibly more relevant, tasks (e.g., exploring gender differences in the choice to prepare for interviews). 

Finally, all of the experiments in this dissertation were performed online, largely to be able to recruit a large number of participants to maximize power in the shortest time possible. However, in-person behavior may be different from online behavior (possibly cite if found), so in-person equivalents of these studies should be run to assess whether these results would replicate when participants make these decisions in the presence of other participants that they may be competing against, for instance. 

## Future directions

There are a number of avenues for future research in this area. First, we encourage future research to test the robustness of gender differences in preparation outside of online and laboratory settings. Do these findings translate to real-world settings (e.g., through field experiments)? Exploring the gender difference in preparation cross-culturally (e.g., among hunter-gatherer populations [@Apicella2014a; @Apicella2012; @Apicella2017; @Apicella2015; @Apicella2009; @Apicella2015a; @Apicella2018; @Apicella2007; @Apicella2014; @Apicella2016; @Apicella2018a; @Apicella2007a]) would also shed light on the universality of the finding and help to identify cultural, ecological and social factors that exacerbate it.

A second important extension of the work would be to examine how anticipated preparation or workload influences women’s decisions to enter competitive environments. While we did not find that giving women time to prepare makes them more likely to compete, it is still possible that women know that they will end up preparing more in competitive situations and thus, select out of them. As mentioned earlier, there are opportunity costs to preparing. 

A third extension of the current work would be to examine whether women are overpreparing. Does preparation negatively impact women? Does it help women? To determine whether men or women are preparing more (or less) than needed, future research should test whether gender and time chosen to prepare interact to affect a participants’ probability of winning a competition [see @Niederle2007]. Another follow-up study could manipulate whether there is a monetary cost for preparing to explore whether gender differences in the choice to prepare persist despite a clear cost, and whether this leads to gender differences in earnings within the study. 

Finally, it would be important to explore the gender difference in preparation and general beliefs about gender differences in preparation further. For instance, manipulating the effects of beliefs about gender differences in preparation on subsequent behavior would show whether stereotypes/beliefs about gender differences causally affect the gender difference in preparation. Understanding the mechanisms underlying the phenomenon would be important to understand if (and how) interventions should be designed to alleviate any of the potentially negative consequences of choosing to prepare indiscriminately and spending too much time preparing when preparation is either costly or there are only marginal returns to preparation. We hypothesize that the gender difference in preparation could be driven by either gender differences in risk, confidence, or by gender stereotypes about gender differences in preparing, but since that was not a foci of our research, we likely did not have sufficient power either statistically and/or by design to identify the precise mechanism underlying this phenomenon and urge other researchers to tackle this question more directly (i.e., experimentally). 

## Summary 

Here we show that preparation has no impact on willingness to compete, while discovering a gender difference in preparation, along with robust perceptions of gender differences in preparation. While we built off an extensive literature on gender differences in competitiveness, we have unearthed a new gender difference in preparation. (Over)preparing may be costly if individuals are not selective in the environments in which they choose to prepare, that is, they are not changing preparation behavior when in a competitive versus non-competitive setting. As this is a new area of research, there are many promising and exciting avenues for future exploration, all of which have the potential to inform policy. First, future work should explore whether these results generalize to other populations and tasks. Second, future work should examine the impact of preparation on performance and payoffs. Do women overprepare relative to their potential payoffs? Do men underprepare? What are the opportunity costs of preparing? Also, it would be important to think about ways that women could be equally rewarded *without* having to compete - that is, reimagining how to support women, and students/workers generally, being productive in ways that work for them. Future work should explore the implications of these findings further in organizational contexts, where these effects may have a long-lasting impact on gender differences in economic outcomes.

