---
output: html_document
---

## Describing goals of research and main descriptive findings

Previous research suggests that women tend to be more risk-averse [@Croson2009; @Dohmen2011b; @Eckel2008; @Bertrand2010a] and less confident [@Bertrand2010; @Lundeberg1994; @Mobius2011; @Barber2001; @Croson2009], which affects their decisions to compete. Since confidence and risk attitudes may be affected by the opportunity to prepare, women may be more likely to compete when they have the opportunity to prepare before entering a competition. Through three experiments, we explored whether the opportunity to prepare affects gender differences in competitiveness and whether there are gender differences in willingness to prepare. 

Within our design framework, we replicate the effect of gender on the choice to compete when gender is included as the only predictor in the model, but the gender difference in the choice to compete goes away when controlling for task score, risk, and confidence across all three studies. There are a couple of possible reasons we do not consistently replicate the gender difference in competitiveness using our study design. There might be something unique about the task or online nature of the competition [@Apicella2020; @Charness2021; @Apicella2017] that leads us to find slightly different effects than the literature. In line with this possibility, @Charness2021 suggest that gender gap in the choice to compete depends on the circumstances and beliefs.

Though we do not consistently find evidence for the the gender difference in competitiveness when controlling for other predictors, we find evidence that gender consistently predicts risk and confidence across studies, replicating previous effects found within the literature [@Croson2009; @Dohmen2011b; @Eckel2008; @Bertrand2010a; @Bertrand2010; @Lundeberg1994; @Mobius2011; @Barber2001]. Next, we explored the effects of our preparation manipulations on the choice to compete across studies. 

## Summarizing effects of preparation condition on choice to compete

First, we find no evidence that preparation increases men or women’s willingness to compete. In fact, in Study 3 we find that women in the control condition were significantly *more* likely to compete than women in the control condition, despite believing that practicing helps performance on the main task both based on their behavior and their responses to the manipulation check question. We explored whether the unexpected effect in Study 3  was driven by increased perceptions of risk or reduced confidence when participants were assigned to the practice condition relative to the control condition, and did not find strong evidence for that possible explanation. 

One possible reason women assigned to the preparation condition competed less is that they did not feel as though they were practicing as much as others, leading them to avoid the competition altogether because they expected to be at a disadvantage if they were to have chosen to compete. That is, even though they might choose to practice multiplication problems, they still may not have felt like they practiced enough relative to others. It is possible that the unlimited nature of the preparation led participants to think more about how much they were preparing relative to others than they would have if all participants were required to practice for the same pre-determined amount of time (like in Study 2). It is also possible the unlimited nature of the preparation, in combination with perceptions of the limited ability of the control task to help with performance on the main task may have led women in the control condition to feel less pressure to prepare for the task and as a result, led them to compete more because they felt more prepared than women in the preparation condition.

Notably, this effect only holds among the subsample of participants that identify as women. When testing this hypothesis among the entire sample of participants, we do not find strong evidence that condition affects the decision to compete, similar to Studies 1 and 2. Thus, if the hypothesized explanation for the effect of condition on the choice to compete is valid, it is possible that women are especially susceptible to feelings of underpreparation relative to others when they have unlimited time to prepare, which may lead to a range of possible adverse outcomes, such as unnecessary overpreparation and a failure to enter competitive environments when they would otherwise outcompete others and earn more. Since we cannot directly test this hypothesis within the context of the current study, we include questions about perceptions of one's own preparation in the study included in Chapter 2 and explore how gender relates to perceptions of relative preparation there. 

## Summarizing effects of gender on practice 

Despite the lack of evidence for the effect of preparation on the choice to compete, we discovered a sizable gender difference in preparation. Here, we focus on the decision to practice problems as our main dependent variable, because it is the most consistent measure of preparation across all studies and had the most power across studies relative to other means of quantifying preparation (e.g., the number of practice problems left empty and the number of practice rounds completed). In Study 1, we found that women were 75.47% [DOUBLE CHECK] more likely to choose to complete practice problems compared to men. We replicated this finding in Study 2, where women were 18.62% [DOUBLE CHECK] more likely to choose to practice problems, even though half of participants were required to prepare for several rounds of practice beforehand. This effect holds despite no strong evidence that there is a gender difference in performance on the multiplication task used and after . Importantly, across two out of the three studies, we find no gender difference in task performance when controlling for gender differences in risk and confidence, so the gender difference in the decision to practice does not seem to be especially. Finding the effect of gender on the decision to practice is especially noteworthy because we are drawing from a participant pool (MTurk) where participants could be earning money for their participation through a nearly limitless supply of other studies, so the opportunity costs of preparing may be greater for MTurkers relative to other participant populations.

### Possible reasons for Study 3 deviation 

Notably, we do not replicate the effect of gender on the choice to practice problems in Study 3. Although we cannot be completely certain what may be underlying our inability to replicate the effect from the previous studies, we describe a few possible explanations here. First, Studies 1 and 2 measured the decision to complete practice problems *after* participants chose to compete, while Study 3 measured the decision to practice problems *before* the decision to compete, as necessitated by the main manipulation within the study. Thus, the differences in the results across studies could be explained by the effects of the decision to compete on the choice to practice that are not captured in Study 3. There are also fewer participants that are offered the opportunity to practice in Study 3 (N = INSERT) relative to Studies 1 (N = INSERT) and 2 (N = INSERT) by nature of the study design (i.e., manipulating unlimited opportunity to prepare) so Study 3 likely had less power to detect the effect than previous studies. Finally, the structure of practicing itself varied across the three studies. For instance, Studies 1 and 2 did not offer participants the opportunity to study multiplication tables as a separate decision from the choice to practice problems, whereas in Study 3, participants were first asked whether they would like to study multiplication tables, *then* afterwards were asked whether they would like to practice problems. Perhaps being asked whether they would like to study before being asked whether they would like to practice problems reduced participants' interest in completing practice problems. Thus, like the gender difference in the choice to compete, it is likely that gender differences in preparation are shaped by context, INSERT BASED ON RESULTS FROM CHAPTER 2: as suggested by the findings in Chapter 2. 

### Describing previous literature with similar effects 

To our knowledge, these studies are the first to demonstrate a gender difference in preparation among adults who must explicitly opt into preparation. However, previous findings within educational contexts *have* found that women are more likely than men to value dedication and mastery [@Leslie2015; @Kenney-Benson2006], emphasize the importance of hard work [@Mccrea2008; @Hirt2009; @Mccrea2008a], and spend more time preparing than men for an intellectual evaluation when they were told that practice improved future performance [@Kimble2005]. For instance, in a study examining school-aged children’s approach to learning math, researchers found that girls, compared to boys, reported being more motivated to “master” their schoolwork and engage in more effortful learning strategies [@Kenney-Benson2006]. In one study looking at whether delaying competition affects gender differences in the willingness to compete while providing opportunity to study, @Charness2021 did not find a significant difference in the choice to prepare (*N* = 202). Although it is worth noting that, though the effect is non-significant, women are directionally more likely to prepare in this study. Since studying gender differences in the choice to prepare was not one of the main foci of their research, contrary to ours, it is entirely possible they did not have sufficient power to detect the effect of gender on the choice to prepare as a result. 

### Possible explanations for the gender difference in preparation

The observed gender difference in preparation may be driven by women's relatively greater desire to reduce uncertainty around their future performance (given their greater average risk aversion) and/or increase their performance (given their lower average confidence). Indeed, mastery is an important driver of confidence [for review, see @Gist1992; @Usher2008]. While it is possible that confidence and risk aversion may be driving the gender difference in preparation, it is important to note that preparation in our studies did not increase competitiveness in either men or women. Because participants were able to choose to prepare in study 2, we are unable identify whether preparation causally affected confidence and/or risk aversion. Future work should examine the bidirectional relationships between confidence and preparation and risk and preparation.  Of course, other explanations for the gender differences in preparation may also exist, including relative differences in real or perceived opportunity costs, how rewarding it is to prepare, and/or enjoyment on the task.


### effects of prep on choice to compete 

Again, we find little evidence that preparation affects willingness to compete. However, it is possible that we may have found an effect of preparation had we given participants unlimited time to prepare so that they mastered the material or reached their desired level of proficiency. In fact, by limiting the amount of time to prepare in Study  2, we may have unintentionally undermined confidence. For instance, participants may have been made more aware of the discrepancy between their current ability and their desired ability. Even more, having limited time to prepare may also have been stressful to participants and to offset this stress, some participants may have opted for the less stressful piece-rate payment scheme. Thus, future work examining the role of preparation on competition should examine how unlimited preparation and perceived level of mastery influence decisions to compete. 

## summary of effects of perceptions of gender diff

Finally, we showed that participants accurately predicted the observed gender differences in preparation and competitiveness, regardless of their own choice to prepare or compete, suggesting that they observe these behaviors directly in their own lives and/or have learned about stereotypes surrounding these behaviors. There is extensive work suggesting that beliefs about identity-based behavior actually affect behavior [@Babcock2012; @Bowles2007; @Toosi2019; @Smith2014; @Benjamin2010c; @Bertrand2015; @Akerlof2000]. Our findings would suggest that any observed gender differences in behavior may be generalizable to other contexts. In both cases, participants' accuracy in predicting the gender differences in competitiveness and preparation would suggest that these are not isolated findings, but in fact are representative of gender differences in other contexts. One step to improve gender equality within organizations is to take these gender differences into account when making decisions on how to organize reward structures and communicate these structures to employees, and to reward cooperation and other forms of work on par with competition.


TO BE INTEGRATED: 
- Finally, we find robust effects of perceptions of gender differences in willingness to compete and practice among participants across all three studies, which seem to generally align with the actual results found.


## conclusion 



While we built off an extensive and laudable literature on gender differences in competitiveness, we have unearthed a new gender difference in preparation. As this is a new area of research, there are many promising and exciting avenues for future exploration, all of which have the potential to inform policy. First, future work should explore whether these results generalize to other populations and tasks. Second, future work should examine the impact of preparation on performance. Do women overprepare? Do men underprepare? What are the opportunity costs to preparing? Also, it would be important to think about ways that women could be equally rewarded *without* having to compete - that is, reimagining how to support women being productive in ways that work for them. And finally, how do competitions themselves affect gender differences in the choice to prepare? 

Much of the research on gender differences in competitiveness is focused on designing interventions to increase women’s competitiveness, with less attention paid to potential downstream consequences of these interventions. Here we show that preparation has no impact on willingness to compete, while discovering a gender difference in preparation. Future work should explore the implications of these findings further where these effects may have a long-lasting impact on gender differences in economic outcomes.

TO BE INTEGRATED: 
- Overall, we do not find strong evidence that practicing affects gender differences in competition. Instead we find evidence for a gender difference in willingness to prepare, along with robust perceptions of gender differences.
    - we also find evidence that competition choice is related to the decision to spend extra time practicing, such that ppts who chose to compete are more likely to choose to practice relative to ppts who chose the piece rate payment scheme.
- thus... it is likely that this gender difference in preparation could be exacerbated when ppts are required to compete. == leading into motivation for next chapter of the dissertation.











## new outline


- in general, there are no effects of the practice condition on gender differences in choice to compete, with the exception of Study  three where women in control condition actually were more likely to compete: practice might actually make things worse for women, perhaps reducing their confidence - especially if it’s unnecessary practice. since this effect only holds among women, perhaps it’s driven by increased perceptions of risk or reduced confidence when practicing, where women in the condition where they are given the option to practice for the main task may feel like they are underperforming relative to other women.
    - perhaps for women they think they are not practicing as much as others in multiplication condition, so they feel like they shouldn’t compete (eg even though they might agree to practice, they still don’t feel like they practiced enough relative to others). whereas when the prep task is clearly irrelevant (ie subtraction), they don’t feel this pressure to practice & as a result, don’t feel underprepared, leading them to compete more.
- replicate effects of gender on choice to compete when gender is included as only predictor in model, but across all three studies, gender diff in choice to compete goes away when controlling for task score, risk, and confidence (like apicella et al). and we find evidence that gender consistently predicts risk & confidence across studies, replicating previous effects.
    - can make a comment about how there might be something unique about the task or online nature (eg like apicella study) that leads us to find slightly different effects than the literature = this is in contrast to the previous studies, which found effects over & above effects of risk & confidence.
- find evidence that women tend to choose to practice more (when measured as the binary choice to practice, before they know what they are getting into)
    - although this effect doesn’t quite replicate in Study three, possibly for one of following reasons:
        - possible explanation is that previous studies measured extra practice AFTER they chose to compete, while this study measures practice before the decision to compete. so there could be effects of the decision to compete or not on choice to practice in previous studies, while decision to practice in new study is made before they choose to compete
        - perhaps it could be that women are far more likely to prepare the closer they get to actually performing - but they don’t feel the need to do so earlier on.
        - there are also fewer ppts that are offered opp to practice in the first place - so there may just be less power (possible option for power analysis: [https://rdrr.io/cran/powerMediation/man/powerLogisticBin.html](https://rdrr.io/cran/powerMediation/man/powerLogisticBin.html)???)
        - finally, it could be explained by the way the practice is structured relative to previous studies (where previous studies didn’t have them make the decision to study first, so perhaps being asked to study first reduced their interest in practicing)
    - importantly across two out of the three studies, we find no gender difference in task performance when controlling for gender differences in risk & confidence
- other ways of measuring practice (eg number of problems left empty; number of rounds of practice) are less robust.
- Finally, we find robust effects of perceptions of gender differences in willingness to compete and practice among participants across all three studies, which seem to generally align with the actual results found.
- Overall, we do not find strong evidence that practicing affects gender differences in competition. Instead we find evidence for a gender difference in willingness to prepare, along with robust perceptions of gender differences.
    - we also find evidence that competition choice is related to the decision to spend extra time practicing, such that ppts who chose to compete are more likely to choose to practice relative to ppts who chose the piece rate payment scheme.
- thus... it is likely that this gender difference in preparation could be exacerbated when ppts are required to compete. == leading into motivation for next chapter of the dissertation.





