---
title             : "The effects of preparation on gender differences in choice to compete"
shorttitle        : "Preparation, gender, and choice to compete"

author: 
  - name          : "Keana Richards"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "3720 Walnut Street, Philadelphia PA 19104"
    email         : "keanari@sas.upenn.edu"
  - name          : "Emily Falk"
    affiliation   : "1,2,3"
  - name          : "Gideon Nave"
    affiliation   : "2"
  - name          : "Coren Apicella"
    affiliation   : "1"


affiliation:
  - id            : "1"
    institution   : "Department of Psychology, University of Pennsylvania, Philadelphia, PA"
  - id            : "2"
    institution   : "Marketing Department, The Wharton School, University of Pennsylvania, Philadelphia, PA"
  - id            : "3"
    institution   : "Annenberg School for Communication, University of Pennsylvania, Philadelphia, PA"

authornote: |
  Correspondence concerning this article should be addressed to Keana S. Richards (email: keanari@sas.upenn.edu) and Coren L. Apicella (email: capicella@psych.upenn.edu), Psychology Department, University of Pennsylvania, 3720 Walnut St., Philadelphia, PA 19104. 

abstract: |
  Previous research suggests that women compete less than men, even when there are no gender differences in performance. This reluctance to compete may result in lower earnings and contribute to the gender wage gap. We conducted three experiments involving over X (will be inserted once last study is run) participants recruited from an online marketplace to causally test whether preparation for a task can reduce gender differences in competitiveness by increasing women's willingness to compete. We test this hypothesis in three experiments using a mathematics task. Specifically, we test whether the gender difference in willingness to compete is reduced by 1) informing participants about an opportunity to practice before the task (Study 1), 2) by allowing participants limited practice before the task (Study 2), and 3) by allowing participants unlimited practice before the task (Study 3). Contrary to our hypotheses, we find no evidence, in any of the studies, that preparation affects willingness to compete in either men or women. Instead, we discover a sizable gender gap in preparation, where, depending on the study, women are between X% and X% more likely to prepare than men, regardless of whether they choose to compete. These findings align with participants' incentivized beliefs: More than X% of participants in each study correctly predicted that women would prepare more than men. Our findings suggest that preparation is ineffective at reducing the gender gap in competitiveness. Instead, we uncover a sizable gender difference in preparation. Given the potential opportunity costs associated with preparing, future work should explore whether women overprepare relative to men.

  
keywords          : "gender, gender differences, choice to compete, competitiveness, preparation, practice"
wordcount         : "XXXX"

bibliography      : ["library.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : yes
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_word
---


\nocite{Richards2020}

# Introduction 


```{r child = here::here("paper",  "intro.Rmd")}

```

# Study 1 

```{r child = here::here("paper", "study1.Rmd")}

```

# Study 2

```{r child = here::here("paper", "study2.Rmd")}

```

# Discussion

```{r child = here::here("paper", "discussion.Rmd")}

```


# Figures 

```{r child = here::here("paper", "figures.Rmd")}

```


\newpage

# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>
\endgroup