---
output:
  word_document: default
  html_document: default
---

### Gender gaps persist despite women's success in education

Women have surpassed men in education outcomes, like college attendance and graduation rates [@Blau2017; @Goldin2006; @Stoet2015], but continue to be underrepresented in top management positions in nearly all sectors [@Bertrand2001]. And, a sizable gender wage gap still persists [@Blau2017]. Traditional economic variables, such as household division of labor and discrimination, account for some, but not all, of these disparities [@Blau2017]. As such, researchers have begun to consider psychological gender differences, including the predilection for competition, as means of understanding persistent gender gaps in labor market outcomes [for review, see @Niederle2011]. Specifically, they expected that gender differences in competitiveness may explain why women may not compete for promotions and are underrepresented in top-level or highly competitive positions (e.g., CEO) [@Niederle2007].

### Gender differences in competitiveness 

Research suggests women are, on average, less competitive than men [for review, see @Niederle2011; @Croson2009; @Niederle2017b; @Shurchkov2018], conditional on ability and other factors relevant to competitiveness. Foundational work on gender differences in competitiveness operationalized competitiveness as the choice of a tournament payment scheme, that reaps potentially higher earnings but requires outperforming an opponent, over a piece-rate scheme, where participants are paid per unit of work they produce [@Niederle2007; although see @Saccardo2018 for an arguably more sensitive test of gender differences in competitiveness]. In this paradigm, women are less likely to enter tournaments while completing mathematical problems, even when they would have earned more by competing [@Niederle2007]. Numerous conceptual replications over the past 15 years suggest that the gender difference in willingness to compete is robust [see @Niederle2011; @Niederle2017a; @Niederle2017b for review]. Notably, this effect has been replicated in diverse populations (e.g., across age groups and cultures) [@Apicella2015; @Buser2014; @Sutter2016; @Andersen2013; @Buser2017b; @Sutter2010; @Dreber2014; @Mayr2012] and with a diverse set of tasks [@Apicella2015; @Saccardo2018; @Bjorvatn2016; @Sutter2015; @Frick2011; @Samek2019]. However, there is evidence that the task used during competition affects the size of the gender gap. For instance, some research suggests that when the task is female-typed or gender-neutral, the gender gap in willingness to compete may be reduced or eliminated [@Iriberri2017; @Boschini2014; @Boschini2019; @Apicella2015; @Grosse2010; @Gunther2010; @Dreber2014; @Dreber2011; @Shurchkov2012]. Drawing from the psychology literature on stereotype threat [@Steele1997; @Spencer1999; @Spencer2016], negative stereotypes about women’s ability to perform male-typed tasks (e.g., math, mental rotation) may produce anxiety and undermine performance. As a result, women may decide not to engage in a competition because they either believe the stereotype or because the stereotype provokes enough anxiety to reduce performance [@Gunther2010; @Grosse2010; @Iriberri2017; @Shurchkov2012]. 

Importantly, this laboratory measure of competitiveness based on the preference between a tournament and piece-rate payment scheme predicts labor market outcomes, including education choices [@Buser2014; @Zhang2012; @Buser2017c; @Buser2017b], entrepreneurial decisions (e.g., investment, employment) [@Berge2015], and both expected and actual earnings [@Reuben2015; @Reuben2017]. Thus, understanding why men and women differ in levels of competitiveness and whether interventions exist that can reduce or eliminate the difference may be key for solving the pernicious gender gaps in the labor market. In fact, many of the most crucial time points during one's career that determine later success (e.g., job interviews, university and post-baccalaureate entrance exams, promotion) require competing against others for a limited number of slots and substantially higher earnings.   

### Risk attitude and confidence as proposed mechanisms for gender difference in competitiveness 

Both confidence and risk attitudes have been implicated in driving gender differences in willingness to compete [@Niederle2011; @Veldhuizen2017]. However, the extent to which confidence and risk attitudes account for the gender difference in willingness to compete is debated. The foundational research in this literature suggests that confidence and risk attitudes do not completely explain gender differences in competitiveness, since a residual gap remained after controlling for these factors [@Niederle2007]. As a result, the unexplained component of the original gender effect was taken as evidence of a distinct “competitiveness” trait, separate from risk attitudes and confidence [@Niederle2007; @Niederle2011]. Conversely, recent work correcting for measurement error [@Gillen2019] and using experimental techniques to isolate the effects of the competitiveness trait [@Veldhuizen2017] suggests that risk attitudes and confidence can fully explain the gender gap in the choice to compete. 

Regardless of whether competitiveness is a “stand-alone” trait, it is clear that both confidence and risk attitudes influence how men and women react to competitions. For instance, even in the original study by @Niederle2007, 27% of the gender gap in tournament entry was explained by men being more overconfident than women about their relative performance on the task.  As such, interventions designed to correct men's overconfidence, increase women’s confidence, or decrease women's perceptions of risk and uncertainty in competitive contexts may help reduce the gender gap in competitiveness.

#### Gender differences in confidence 

Within the literature on the gender gap in competitiveness, confidence is operationalized as the belief about one’s relative performance during a competition, where individuals who have inaccurately high (low) ratings of their performance are deemed overconfident (underconfident) [@Niederle2011; also see overplacement in @Moore2008; @Moore2017]. If an individual does not believe their performance is higher than the individuals they are competing against, they are unlikely to make the decision to compete for fear of losing.

While most individuals are overconfident [@Alicke2013; @Dunning2004b], there is ample research to suggest that women are less (over)confident on average than men across a number of domains [@Mobius2011; @Niederle2011; @Croson2009; @Lundeberg1994; @Niederle2007; @Bertrand2010a; @Beyer1990; @Beyer1997; @Jakobsson2013; although see @Bandiera2022]. Because women are less overconfident, they compete less often than they should, given their actual ability [@Niederle2007]. Confidence too may help explain why, in some situations, the gender gap in competitiveness may be reduced or eliminated. For instance, women tend to compete more when tasks are female-typed or gender-neutral [@Iriberri2017; @Boschini2014; @Boschini2019; @Apicella2015; @Grosse2010; @Gunther2010; @Dreber2014; @Dreber2011; @Shurchkov2012], when they are facing other women [@DattaGupta2013; @Booth2012], or when competing against themselves [@Apicella2017a; @Bonte2018; @Carpenter2018; @Apicella2020]. For example, @Apicella2017a document a gender difference in confidence when women and men are competing against other individuals, but not when they are competing against themselves (i.e., their own past performance). There are several non-mutually exclusive and potentially interacting explanations that could account for women’s relatively lower (over)confidence, including differences in performance or ability, experience, innate psychological differences, and stereotype threat [@Steele1997; @Spencer1999; @Spencer2016]. In the latter case, for instance, women may decide to forgo competitions because they either believe negative stereotypes about their ability to perform certain tasks, or because stereotypes provoke enough anxiety to reduce confidence [@Gunther2010; @Grosse2010; @Iriberri2017; @Shurchkov2012; @Burow2017]. Taken together, this body of research suggests that interventions designed to increase confidence in women may embolden them to compete more. 

#### Gender differences in risk attitude

A second variable that has been identified as a possible explanation for gender differences in competitiveness is risk attitudes, typically construed as the preference for a certain gain over a gamble, even if the gamble has an equal or greater monetary expectation [@Kahneman1982]. Researchers investigating gender differences in risk attitudes find that men are typically more risk-seeking than women [@Eckel2008; @Charness2012; @Croson2009; @Bertrand2010a], including in hunter-gatherers [@Apicella2017], but see [@Harrison2007] for an exception. While most studies report a gender difference, the difference appears to be small to medium [@Filippin2016] and culturally-dependent [@Gneezy2009].  

Competitive payment schemes are inherently riskier than piece-rate payment schemes because the variance in returns is greater. With piece-rate payment schemes, individuals are guaranteed a certain amount for every unit they produce. Moreover, there typically exists uncertainty in competitions since one’s relative performance is unknown [@Niederle2011]. Indeed, some of the gender gap in competitiveness is explained by men and women’s differing risk attitudes [@Niederle2011]. In fact, some recent work suggests that nearly 30% of the gender gap in competitive choices can be explained by risk attitudes [@Gillen2019; @Veldhuizen2017]. 

### Why preparation may eliminate gender gap in competitiveness by changing confidence and/or risk attitude  

Preparation or training on a task may increase one's confidence [@Gist1992; @Schunk1981; @Schunk1982; @Usher2008], since people usually are able to observe an improvement in their performance over time. In fact, there is evidence that preparation (as measured through studying) does causally affect academic performance among university students [@Stinebrickner2008]. In line with increased confidence after preparation or training, @Lent1996 found that college students listed past accomplishments as the most influential factor in determining their confidence. Moreover, research directly comparing the effects of mastery experiences (via preparation), vicarious experiences (e.g., watching others perform a task), and a control treatment without any intervention on confidence found that mastery increased confidence significantly more than vicarious experiences and the control treatment [@Bandura1977a]. Other research suggests that women are less likely to be confident in their answers when asked about topics outside of their field of expertise, leading to a confidence gap [@Sarsons2021]. This suggests that gaining expertise, perhaps through practicing, may selectively boost women’s confidence. @Roll2011 found that practicing mathematics problems, using an intelligent tutoring system, significantly decreases underconfidence but has no effect on rates of overconfidence. This too suggests that practicing may preferentially benefit women who are more likely than men to be underconfident. That said, if practicing only helps with underconfidence, when most people, including women, are overconfident, then its application may be limited. 

Preparation, and the feelings of preparedness or self-efficacy that follow, may also decrease the perceived riskiness of competitions. With increased self-efficacy, individuals may believe their probability of winning in a competition is higher than those with lower self-efficacy. Surprisingly little work has explored how preparation impacts men's and women's risk attitudes. However, some experimental work suggests that manipulating perceived competence on a task by giving participants positive feedback about their performance on a task can lead to significantly more risk-taking behavior [@Krueger1994]. The researchers were able to rule out the role of mood in driving the results by giving some participants positive feedback on one task and negative feedback on another. For these participants, risk-taking increased in the positive feedback condition and decreased in the negative feedback condition. Interestingly, @Gysler2002 find that knowledge – in this case, understanding of financial markets – and confidence in that knowledge, negatively correlate with women’s risk aversion, but positively correlate with men’s risk aversion. This suggests that preparation may disproportionately increase risk-taking in women. Finally, there is evidence that risk attitudes play a greater role in predicting decisions to compete when individuals are competing against other individuals, rather than themselves (i.e., their own past performance), possibly because there is more uncertainty in estimating an opponent’s ability versus one’s own ability [@Apicella2017a]. 


### Previous literature looking at preparation on competition entry 

Surprisingly, little work has explored how preparation impacts men and women’s confidence, risk attitudes, or their willingness to compete. We know of only one study that has explored how delaying a competition, and in some cases, offering an opportunity to study, affects decisions to compete. In a working paper, @Charness2021 examine whether gender gap entry rates change when a future opportunity to study for the task is made available. The authors hypothesized that women would be more likely to compete when there is an opportunity to study for the task. Contrary to their prediction, the authors found that providing an option to study leads men to be more likely to enter into future planned tournaments and leads women to be less likely to enter into these tournaments, resulting in a significant gender gap. However, this gap was only present during the initial, provisional sign-up period. When the actual choice was made later – sometime between one and five days – the gender difference disappeared. Of those men who returned to complete the study, some switched into the non-competitive payment scheme. The authors suggest that the results may be explained by men being overly confident in their future selves’ resolve to study. 


### The current experiments 

We examine the role of preparation on the gender differences in willingness to compete through three experiments. However, unlike @Charness2021, we do not introduce a significant time delay in our studies. That is, experiments took place in a single session, thus minimizing any potential for gender differences in beliefs about future behavior to affect our results. 

In the first experiment, we test whether simply knowing that there will be an opportunity to prepare before performing a task affects the gender gap in willingness to compete. That is, we manipulate participants’ knowledge of whether they will have time to prepare before they make their decision to compete. We anticipated that participants with this information would be more inclined to compete compared to participants without this information and that this effect would be stronger for women. Thus, we expected a main effect of condition and an interaction between gender and condition on the choice to compete. In the second experiment, we examined how actual preparation influences the decision to compete. That is, we manipulated whether participants were required to prepare before making the decision to compete. Again, we expected that women in the preparation condition would be more inclined to compete than women in the no preparation condition, while we did not expect men's competitiveness to be significantly affected by the preparation manipulation.

Finally, in experiment 3, we examine how an unlimited amount of preparation affects gender differences in the willingness to compete. Across all experiments, we measured gender differences in actual preparation after administering the treatment and eliciting preferences to compete. Finally, we monetarily incentivized participants in both studies to correctly predict whether men or women would prepare and compete more. The research design, pre-registered hypotheses, measures and analyses are available on [OSF](https://osf.io/q39a5/) and all analyses were conducted in R statistical software (version `r paste0(R.Version()$major,".", R.Version()$minor)`). All participants across the three experiments were recruited through Amazon Mechanical Turk (or MTurk), with a guaranteed payment and the opportunity to earn bonuses depending on their performance and the performance of others. Recruiting participants on this platform allowed for efficient data collection while meeting acceptable psychometric standards, such as high test-retest and alpha reliability [@Rand2012; @Buhrmester2011; @Paolacci2014;@Chandler2016].
